# START TRAINING

In [49]:
import ast
import json
import warnings

import pandas as pd
from snowflake.ml.modeling.impute import SimpleImputer
from snowflake.ml.modeling.metrics import accuracy_score
from snowflake.ml.modeling.model_selection import GridSearchCV
from snowflake.ml.modeling.preprocessing import OneHotEncoder
from snowflake.ml.modeling.xgboost import XGBClassifier
from snowflake.ml.registry import Registry
from snowflake.ml.utils.connection_params import SnowflakeLoginOptions
from snowflake.snowpark import Session
from snowflake.snowpark import types as T
from snowflake.snowpark.functions import col
from snowflake.snowpark import functions as F
from snowflake.snowpark.functions import when, lit

import numpy as np

warnings.simplefilter(action="ignore", category=UserWarning)

In [50]:
session = Session.builder.configs(SnowflakeLoginOptions()).getOrCreate()

In [51]:
final = (
    session.table("MEN.FINAL_FEATURES")
    .with_column_renamed("WTEAMID", "W_TEAMID")
    .with_column_renamed("LTEAMID", "L_TEAMID")
    .with_column_renamed("WSCORE", "W_SCORE")
    .with_column_renamed("LSCORE", "L_SCORE")
)

In [52]:
final.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"SEASON"  |"W_TEAMID"  |"L_TEAMID"  |"W_SCORE"  |"L_SCORE"  |"ROUND"  |"W_CONF"    |"L_CONF"    |"W_REGION"  |"W_SEED"  |"L_REGION"  |"L_SEED"  |"W_SCORE_MEAN"  |"W_FGM_MEAN"  |"W_FGA_MEAN"  |"W_FGM3_MEAN"  |"W_FGA3_MEAN"  |"W_FTM_MEAN"  |"W_FTA_MEAN"  |"W_OR_MEAN"  |"W_DR_MEAN"  |"W_AST_MEAN"  |"W_TO_MEAN"  |"W_STL_MEAN"  |"W_BLK_MEAN"  |"W_PF_MEAN"  |"W_SCORE_MEDIAN"  |"W_FGM_MEDIAN"  |"W_FGA_MEDIAN"  |"W_FGM3_MEDIAN"  |"W_FGA3_MEDIAN"  |"W_FTM_MEDIAN"  |"W_FTA_MEDIAN"  |"W_OR_MEDIAN"  |"W_DR_MEDIAN"  |"W_AST_MEDIAN"  |"W_TO_MEDIAN"  |"W_STL_MEDIAN"  |"W_BLK_MEDIAN"  |"W_PF_MEDIAN"  |"W_SCORE_STDDEV"    |"W_FGM_STDDEV"      |"W_FGA_STDDEV"      |"W_FGM3_STDDEV"     |"W_FGA3_STDDEV"     |"W_FTM_STDDEV"      |"W_FTA_STDDEV"     |"W_OR_STDDEV"       |"W_DR_STDDEV"      |"W_AST_STDDEV"      |"W_TO_STDDEV"       |"W_STL_STDDEV"      |"W_BLK_STDDEV"      |"W_PF_STDDEV"       |"W_WLOCN"  |"W_WLOCH"  |"W_WLOCA"  |"W_WINMARGINMEDIAN"  |"W_WINMARGINMEAN"  |"W_LOSEMARGINMEDIAN"  |"W_LOSEMARGINMEAN"  |"W_WON_CONFERENCE"  |"W_TOTAL_WINS"  |"L_SCORE_MEAN"  |"L_FGM_MEAN"  |"L_FGA_MEAN"  |"L_FGM3_MEAN"  |"L_FGA3_MEAN"  |"L_FTM_MEAN"  |"L_FTA_MEAN"  |"L_OR_MEAN"  |"L_DR_MEAN"  |"L_AST_MEAN"  |"L_TO_MEAN"  |"L_STL_MEAN"  |"L_BLK_MEAN"  |"L_PF_MEAN"  |"L_SCORE_MEDIAN"  |"L_FGM_MEDIAN"  |"L_FGA_MEDIAN"  |"L_FGM3_MEDIAN"  |"L_FGA3_MEDIAN"  |"L_FTM_MEDIAN"  |"L_FTA_MEDIAN"  |"L_OR_MEDIAN"  |"L_DR_MEDIAN"  |"L_AST_MEDIAN"  |"L_TO_MEDIAN"  |"L_STL_MEDIAN"  |"L_BLK_MEDIAN"  |"L_PF_MEDIAN"  |"L_SCORE_STDDEV"    |"L_FGM_STDDEV"      |"L_FGA_STDDEV"      |"L_FGM3_STDDEV"     |"L_FGA3_STDDEV"     |"L_FTM_STDDEV"      |"L_FTA_STDDEV"     |"L_OR_STDDEV"       |"L_DR_STDDEV"       |"L_AST_STDDEV"      |"L_TO_STDDEV"       |"L_STL_STDDEV"      |"L_BLK_STDDEV"      |"L_PF_STDDEV"       |"L_WLOCN"  |"L_WLOCH"  |"L_WLOCA"  |"L_WINMARGINMEDIAN"  |"L_WINMARGINMEAN"  |"L_LOSEMARGINMEDIAN"  |"L_LOSEMARGINMEAN"  |"L_WON_CONFERENCE"  |"L_TOTAL_WINS"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2003      |1393        |1328        |63         |47         |6        |BIG_EAST    |BIG_TWELVE  |W           |3         |W           |1         |80.103448       |29.241379     |62.206897     |5.241379       |15.862069      |16.379310     |23.620690     |14.310345    |26.896552    |14.965517     |13.620690    |8.310345      |7.275862      |16.586207    |82.000            |29.000          |62.000          |5.000            |16.000           |17.000          |22.000          |14.000         |26.000         |14.000          |13.000         |9.000           |6.000           |17.000         |13.43860331284468   |6.769971344104789   |10.30041368101301   |2.415059419558865   |4.3648280607602405  |6.3606704049180225  |7.757087984546779  |5.568427875082876   |5.287078777548146  |5.666207814755826   |3.940755891957785   |2.465525907387712   |2.9748536098436844  |3.9235301706498955  |1          |17         |6          |9.000                |14.416667          |13.000                |10.000000           |0                   |24.0            |71.166667       |25.266667     |56.533333     |7.466667       |18.966667      |13.166667     |18.600000     |12.133333    |24.966667    |14.166667     |11.800000    |6.933333      |3.766667      |18.600000    |69.500            |25.000          |55.500          |8.000            |19.000           |14.500          |19.500          |11.000         |24.500         |14.000          |11.000         |7.000           |4.000           |18.000         |13.769239412545632  |5.368704592357452   |6.273828177436803   |2.8251741539239665  |5.215912863535969   |5.458832384310769   |7.407358908544935  |4.264798471205879   |4.038464435896397   |5.2528043938452535  |2.808852968740087   |3.423381369348148   |2.028815417922488   |4.148950831234325   |4          |15         |5          |12.500               |15.541667          |6.000                 |7.166667            |1                   |24.0            |
|2003      |1120        |1448        |68         |62         |2        |SEC         |ACC         |W           |10        |W           |2         |70.100000       |25.700000     |54.700000     |5.633333       |16.333333      |13.066667     |19.733333     |11.933333    |22.566667    |13.400000     |15.900000    |8.033333      |4.966667      |16.366667    |69.500            |25.500          |54.500          |5.000            |16.000           |13.000          |18.000          |12.000         |22.000         |14.000          |16.000         |7.000           |4.500           |16.500         |14.41347550037811   |5.9256892426113605  |6.046657671805144   |2.484202890264803   |5.664976081149858   |6.3187369782259495  |8.432013460615442  |3.183289650660147   |5.568899711792268  |5.055553481074055   |4.692988173861085   |3.285110957030219   |2.5928727311613273  |3.9258940383051604  |3          |13         |3          |15.000               |16.157895          |17.000                |15.545455           |0                   |19.0            |78.413793       |26.137931     |57.241379     |6.103448       |17.724138      |20.034483     |26.620690     |14.758621    |26.931034    |14.586207     |15.103448    |6.413793      |4.379310      |18.482759    |75.000            |25.000          |57.000          |6.000            |18.000           |19.000          |25.000          |14.000         |27.000         |14.000          |15.000         |7.000           |5.000           |18.000         |11.977709171623763  |4.525516103164367   |6.743542763266205   |2.1438421117237154  |3.272139514140557   |6.721409078459665   |8.796971069635276  |4.23973690221457    |5.324679990384398   |4.127583554575243   |4.730937856281775   |3.235045131060771   |1.801066906030978   |4.3803187098657554  |1          |16         |7          |11.500               |15.666667          |10.000                |12.600000           |0                   |24.0            |
|2003      |1139        |1257        |79         |71         |2        |HORIZON     |CUSA        |W           |12        |W           |4         |68.586207       |24.068966     |50.655172     |8.482759       |21.862069      |11.965517     |16.551724     |7.827586     |20.379310    |12.965517     |10.413793    |6.344828      |1.862069      |16.068966    |68.000            |23.000          |50.000          |9.000            |21.000           |11.000          |15.000          |7.000          |21.000         |13.000          |10.000         |6.000           |2.000           |16.000         |7.798888382327317   |3.261584124317507   |5.595124574127014   |2.5721127502502688  |4.680690867810007   |5.30823322773218    |6.299581652776634  |2.8418928551231484  |4.246122584193725  |3.6886191183151453  |4.187713696039881   |2.8694929865744574  |1.432384026719092   |4.415322638267786   |3          |11         |10         |12.000               |11.500000          |10.000                |10.800000           |0                   |24.0            |81.833333       |27.966667     |60.833333     |8.433333       |23.400000      |17.466667     |25.100000     |13.200000    |25.100000    |16.600000     |13.366667    |7.200000      |4.733333      |22.666667    |81.000            |28.000          |62.000          |9.000            |24.000           |18.000          |25.500          |13.500         |25.000         |16.000          |12.000         |6.500           |4.500           |22.000         |10.90739492271184   |5.549049828574258   |6.8485253157157855  |2.686920170008778   |4.132295003989913   |6.916912461496097   |8.968719585314282  |3.836305644757727   |4.4049345057560165  |4.445842664782459   |4.398144836178091   |3.6045947067596935  |2.6901267628124885  |5.351978886355962   |0          |16         |8          |18.000               |18.333333          |4.000                 |6.500000            |1                   |24.0            |
|2003      |1139        |1280        |47         |46         |1        |HORIZON     |SEC         |W           |12        |W           |5         |68.586207       |24.068966     |50.655172     |8.482759       |21.862069      |11.965517     |16.551724     |7.827586     |20.379310    |12.965517     |10.413793    |6.344828      |1.862069      |16.068966    |68.000            |23.000          |50.000          |9.000            |21.000           |11.000          |15.000          |7.000          |21.000         |13.000          |10.000         |6.000           |2.000           |16.000         |7.798888382327317   |3.261584124317507   |5.595124574127014   |2.5721127502502688  |4.680690867810007   |5.30823322773218    |6.299581652776634  |2.8418928551231484  |4.246122584193725  |3.6886191183151453  |4.187713696039881   |2.8694929865744574  |1.432384026719092   |4.415322638267786   |3          |11         |10         |12.000               |11.500000          |10.000                |10.800000           |0                   |24.0            |70.166667       |26.333333     |55.800000     |5.566667       |16.200000      |11.933333     |17.633333     |12.666667    |24.600000    |14.500000     |15.633333    |8.733333      |3.733333      |15.900000    |68.000            |25.500          |56.000          |5.000            |17.500           |10.500          |16.500          |12.000         |23.500         |14.000          |14.500         |8.000           |3.500           |15.500         |12.45151516884592   |5.247878619023119   |7.452840263953066   |2.5822114553227435  |4.7080268690822065  |5.680780228102474   |7.136517708238381  |4.357580291859233   |5.745162921971839   |3.3295956210927478  |3.8190387534037935  |2.9353180406899693  |1.964044551429524   |3.273193089324246   |5          |12         |4          |16.000               |17.190476          |7.000                 |6.777778            |0                   |21.0            |
|2003      |1393        |1329        |68         |56         |2        |BIG_EAST    |BIG_TWELVE  |W           |3         |W           |6         |80.103448       |29.241379     |62.206897     |5.241379       |15.862069      |16.379310     |23.620690     |14.310345    |26.896552    |14.965517     |13.620690    |8.310345      |7.275862      |16.586207    |82.000            |29.000          |62.000          |5.000            |16.000           |17.000          |22.000          |14.000         |26.000         |14.000          |13.000         |9.000           |6.000           |17.000         |13.43860331284468   |6.769971344104789   |10.30041368101301   |2.415059419558865   |4.3648280607602405  |6.3606704049180225  |7.757087984546779  |5.568427875082876   |5.287078777548146  |5.666207814755826   |3.940755891957785   |2.465525907387712   |2.9748536098436844  |3.9235301706498955  |1          |17         |6          |9.000                |14.416667          |13.000                |10.000000           |0                   |24.0            |68.724138       |24.655172     |55.413793     |4.862069       |12.965517      |14.551724     |22.344828     |12.379310    |24.068966    |12.241379     |14.655172    |8.793103      |5.586207      |20.137931    |68.000            |24.000          |56.000          |4.000            |13.000           |14.000          |21.000          |12.000         |24.000         |12.000          |15.000         |8.000           |5.000           |18.000         |11.777389226819329  |4.790435888309121   |4.7019542745543585  |2.682271611899138   |3.9141023236497023  |4.982728770463028   |6.688347329497773  |3.121512774281086   |4.366520582798162   |4.197407175864643   |3.4772306509634934  |3.5393635021003425  |3.510364653422775   |4.9405330684046636  |2          |13         |5          |11.500               |13.800000          |11.000                |9.666667            |0                   |20.0            |
|2003      |1120        |1386        |65         |63         |1        |SEC         |A_TEN       |W           |10        |W           |7         |70.100000       |25.700000     |54.700000     |5.633333       |16.333333      |13.066667     |19.733333     |11.933333    |22.566667    |13.400000     |15.900000    |8.033333      |4.966667      |16.366667    |69.500            |25.500          |54.500          |5.000            |16.000           |13.000          |18.000          |12.000         |22.000         |14.000          |16.000         |7.000           |4.500           |16.500         |14.41347550037811   |5.9256892426113605  |6.046657671805144   |2.484202890264803   |5.664976081149858   |6.3187369782259495  |8.432013460615442  |3.183289650660147   |5.568899711792268  |5.055553481074055   |4.692988173861085   |3.285110957030219   |2.5928727311613273  |3.9258940383051604  |3          |13         |3          |15.000               |16.157895          |17.000                |15.545455           |0                   |19.0            |70.620690       |24.241379     |54.413793     |8.034483       |21.862069      |14.103448     |20.655172     |11.172414    |24.137931    |14.000000     |12.931034    |7.206897      |5.551724      |18.758621    |73.000            |24.000          |55.000          |7.000            |22.000           |13.000          |18.000          |12.000         |24.000         |13.000          |12.000         |6.000           |5.000           |19.000         |10.390290082572285  |4.509158679842615   |6.716276795963668   |3.0645759902472642  |4.634684023749624   |6.393885594847628   |7.825215013020409  |3.6358234280558785  |3.7770371986518745  |4.898979485566356   |2.9632394435819727  |3.529258420688403   |2.0973828930359857  |4.214390110087105   |4          |11         |8          |17.000               |16.043478          |7.000                 |6.666667            |0                   |23.0            |
|2003      |1328        |1143        |74         |65         |2        |BIG_TWELVE  |PAC_TEN     |W           |1         |W           |8         |71.166667       |25.266667     |56.533333     |7.466667       |18.966667      |13.166667     |18.600000     |12.133333    |24.966667    |14.166667     |11.800000    |6.933333      |3.766667      |18.600000    |69.500            |25.000          |55.500          |8.000            |19.000           |14.500          |19.500          |11.000         |24.500         |14.000          |11.000         |7.000           |4.000           |18.000         |13.769239412545632  |5.368704592357452   |6.273828177436803   |2.8251741539239665  |5.215912863535969   |5.458832384310769   |7.407358908544935  |4.264798471205879   |4.038464435896397  |5.2528043938452535  |2.808852968740087   |3.423381369348148   |2.028815417922488   |4.148950831234325   |4          |15         |5          |12.500               |15.541667          |6.000                 |7.166667            |1                   |24.0            |74.482759       |27.344828     |58.724138     |6.413793       |17.034483      |13.379310     |19.517241     |11.241379    |24.379310    |16.000000     |14.172414    |6.551724      |2.793103      |17.103448    |75.000            |27.000          |58.000          |6.000            |18.000           |13.000          |19.000          |11.000         |22.000         |17.000          |14.000         |7.000           |3.000           |18.000         |7.75804047424348    |3.5383193750706     |7.864461456450785   |2.542738091113593   |4.6173798847398295  |5.753345548461347   |7.395078904244363  |3.897390793851702   |5.512413264623762   |4.140393338802486   |4.464694614416533   |2.640159654263355   |1.6339984700115238  |3.744947396159257   |1          |13         |7          |10.000               |10.380952          |12.500                |10.125000           |0                   |21.0            |

In [53]:
OHE = OneHotEncoder(
    input_cols=["W_CONF","L_CONF"],
    output_cols=["W_CONF","L_CONF"],
    drop_input_cols=True,
    drop="first",
    handle_unknown="ignore",
)

final = OHE.fit(final).transform(final)
final.show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"W_CONF_ACC"  |"W_CONF_AEC"  |"W_CONF_A_SUN"  |"W_CONF_A_TEN"  |"W_CONF_BIG_EAST"  |"W_CONF_BIG_SKY"  |"W_CONF_BIG_SOUTH"  |"W_CONF_BIG_TEN"  |"W_CONF_BIG_TWELVE"  |"W_CONF_BIG_WEST"  |"W_CONF_CAA"  |"W_CONF_CUSA"  |"W_CONF_HORIZON"  |"W_CONF_IVY"  |"W_CONF_MAAC"  |"W_CONF_MAC"  |"W_CONF_MEAC"  |"W_CONF_MID_CONT"  |"W_CONF_MVC"  |"W_CONF_MWC"  |"W_CONF_NEC"  |"W_CONF_OVC"  |"W_CONF_PAC_TEN"  |"W_CONF_PAC_TWELVE"  |"W_CONF_PATRIOT"  |"W_CONF_SEC"  |"W_CONF_SOUTHERN"  |"W_CONF_SOUTHLAND"  |"W_CONF_SUMMIT"  |"W_CONF_SUN_BELT"  |"W_CONF_SWAC"  |"W_CONF_WAC"  |"W_CONF_WCC"  |"L_CONF_ACC"  |"L_CONF_AEC"  |"L_CONF_A_SUN"  |"L_CONF_A_TEN"  |"L_CONF_BIG_EAST"  |"L_CONF_BIG_SKY"  |"L_CONF_BIG_SOUTH"  |"L_CONF_BIG_TEN"  |"L_CONF_BIG_TWELVE"  |"L_CONF_BIG_WEST"  |"L_CONF_CAA"  |"L_CONF_CUSA"  |"L_CONF_HORIZON"  |"L_CONF_IVY"  |"L_CONF_MAAC"  |"L_CONF_MAC"  |"L_CONF_MEAC"  |"L_CONF_MID_CONT"  |"L_CONF_MVC"  |"L_CONF_MWC"  |"L_CONF_NEC"  |"L_CONF_OVC"  |"L_CONF_PAC_TEN"  |"L_CONF_PAC_TWELVE"  |"L_CONF_PATRIOT"  |"L_CONF_SEC"  |"L_CONF_SOUTHERN"  |"L_CONF_SOUTHLAND"  |"L_CONF_SUMMIT"  |"L_CONF_SUN_BELT"  |"L_CONF_SWAC"  |"L_CONF_WAC"  |"L_CONF_WCC"  |"SEASON"  |"W_TEAMID"  |"L_TEAMID"  |"W_SCORE"  |"L_SCORE"  |"ROUND"  |"W_REGION"  |"W_SEED"  |"L_REGION"  |"L_SEED"  |"W_SCORE_MEAN"  |"W_FGM_MEAN"  |"W_FGA_MEAN"  |"W_FGM3_MEAN"  |"W_FGA3_MEAN"  |"W_FTM_MEAN"  |"W_FTA_MEAN"  |"W_OR_MEAN"  |"W_DR_MEAN"  |"W_AST_MEAN"  |"W_TO_MEAN"  |"W_STL_MEAN"  |"W_BLK_MEAN"  |"W_PF_MEAN"  |"W_SCORE_MEDIAN"  |"W_FGM_MEDIAN"  |"W_FGA_MEDIAN"  |"W_FGM3_MEDIAN"  |"W_FGA3_MEDIAN"  |"W_FTM_MEDIAN"  |"W_FTA_MEDIAN"  |"W_OR_MEDIAN"  |"W_DR_MEDIAN"  |"W_AST_MEDIAN"  |"W_TO_MEDIAN"  |"W_STL_MEDIAN"  |"W_BLK_MEDIAN"  |"W_PF_MEDIAN"  |"W_SCORE_STDDEV"    |"W_FGM_STDDEV"      |"W_FGA_STDDEV"      |"W_FGM3_STDDEV"     |"W_FGA3_STDDEV"     |"W_FTM_STDDEV"      |"W_FTA_STDDEV"     |"W_OR_STDDEV"       |"W_DR_STDDEV"      |"W_AST_STDDEV"      |"W_TO_STDDEV"       |"W_STL_STDDEV"      |"W_BLK_STDDEV"      |"W_PF_STDDEV"       |"W_WLOCN"  |"W_WLOCH"  |"W_WLOCA"  |"W_WINMARGINMEDIAN"  |"W_WINMARGINMEAN"  |"W_LOSEMARGINMEDIAN"  |"W_LOSEMARGINMEAN"  |"W_WON_CONFERENCE"  |"W_TOTAL_WINS"  |"L_SCORE_MEAN"  |"L_FGM_MEAN"  |"L_FGA_MEAN"  |"L_FGM3_MEAN"  |"L_FGA3_MEAN"  |"L_FTM_MEAN"  |"L_FTA_MEAN"  |"L_OR_MEAN"  |"L_DR_MEAN"  |"L_AST_MEAN"  |"L_TO_MEAN"  |"L_STL_MEAN"  |"L_BLK_MEAN"  |"L_PF_MEAN"  |"L_SCORE_MEDIAN"  |"L_FGM_MEDIAN"  |"L_FGA_MEDIAN"  |"L_FGM3_MEDIAN"  |"L_FGA3_MEDIAN"  |"L_FTM_MEDIAN"  |"L_FTA_MEDIAN"  |"L_OR_MEDIAN"  |"L_DR_MEDIAN"  |"L_AST_MEDIAN"  |"L_TO_MEDIAN"  |"L_STL_MEDIAN"  |"L_BLK_MEDIAN"  |"L_PF_MEDIAN"  |"L_SCORE_STDDEV"    |"L_FGM_STDDEV"      |"L_FGA_STDDEV"      |"L_FGM3_STDDEV"     |"L_FGA3_STDDEV"     |"L_FTM_STDDEV"      |"L_FTA_STDDEV"     |"L_OR_STDDEV"       |"L_DR_STDDEV"       |"L_AST_STDDEV"      |"L_TO_STDDEV"       |"L_STL_STDDEV"      |"L_BLK_STDDEV"      |"L_PF_STDDEV"       |"L_WLOCN"  |"L_WLOCH"  |"L_WLOCA"  |"L_WINMARGINMEDIAN"  |"L_WINMARGINMEAN"  |"L_LOSEMARGINMEDIAN"  |"L_LOSEMARGINMEAN"  |"L_WON_CONFERENCE"  |"L_TOTAL_WINS"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|0.0           |0.0           |0.0             |0.0             |1.0                |0.0               |0.0                 |0.0               |0.0                  |0.0                |0.0           |0.0            |0.0               |0.0           |0.0            |0.0           |0.0            |0.0                |0.0           |0.0           |0.0           |0.0           |0.0               |0.0                  |0.0               |0.0           |0.0                |0.0                 |0.0              |0.0                |0.0            |0.0           |0.0           |0.0           |0.0           |0.0             |0.0             |0.0                |0.0               |0.0                 |0.0               |1.0                  |0.0                |0.0           |0.0            |0.0               |0.0           |0.0            |0.0           |0.0            |0.0                |0.0           |0.0           |0.0           |0.0           |0.0               |0.0                  |0.0               |0.0           |0.0                |0.0                 |0.0              |0.0                |0.0            |0.0           |0.0           |2003      |1393        |1328        |63         |47         |6        |W           |3         |W           |1         |80.103448       |29.241379     |62.206897     |5.241379       |15.862069      |16.379310     |23.620690     |14.310345    |26.896552    |14.965517     |13.620690    |8.310345      |7.275862      |16.586207    |82.000            |29.000          |62.000          |5.000            |16.000           |17.000          |22.000          |14.000         |26.000         |14.000          |13.000         |9.000           |6.000           |17.000         |13.43860331284468   |6.769971344104789   |10.30041368101301   |2.415059419558865   |4.3648280607602405  |6.3606704049180225  |7.757087984546779  |5.568427875082876   |5.287078777548146  |5.666207814755826   |3.940755891957785   |2.465525907387712   |2.9748536098436844  |3.9235301706498955  |1          |17         |6          |9.000                |14.416667          |13.000                |10.000000           |0                   |24.0            |71.166667       |25.266667     |56.533333     |7.466667       |18.966667      |13.166667     |18.600000     |12.133333    |24.966667    |14.166667     |11.800000    |6.933333      |3.766667      |18.600000    |69.500            |25.000          |55.500          |8.000            |19.000           |14.500          |19.500          |11.000         |24.500         |14.000          |11.000         |7.000           |4.000           |18.000         |13.769239412545632  |5.368704592357452   |6.273828177436803   |2.8251741539239665  |5.215912863535969   |5.458832384310769   |7.407358908544935  |4.264798471205879   |4.038464435896397   |5.2528043938452535  |2.808852968740087   |3.423381369348148   |2.028815417922488   |4.148950831234325   |4          |15         |5          |12.500               |15.541667          |6.000                 |7.166667            |1                   |24.0            |
|0.0           |0.0           |0.0             |0.0             |0.0                |0.0               |0.0                 |0.0               |0.0                  |0.0                |0.0           |0.0            |0.0               |0.0           |0.0            |0.0           |0.0            |0.0                |0.0           |0.0           |0.0           |0.0           |0.0               |0.0                  |0.0               |1.0           |0.0                |0.0                 |0.0              |0.0                |0.0            |0.0           |0.0           |1.0           |0.0           |0.0             |0.0             |0.0                |0.0               |0.0                 |0.0               |0.0                  |0.0                |0.0           |0.0            |0.0               |0.0           |0.0            |0.0           |0.0            |0.0                |0.0           |0.0           |0.0           |0.0           |0.0               |0.0                  |0.0               |0.0           |0.0                |0.0                 |0.0              |0.0                |0.0            |0.0           |0.0           |2003      |1120        |1448        |68         |62         |2        |W           |10        |W           |2         |70.100000       |25.700000     |54.700000     |5.633333       |16.333333      |13.066667     |19.733333     |11.933333    |22.566667    |13.400000     |15.900000    |8.033333      |4.966667      |16.366667    |69.500            |25.500          |54.500          |5.000            |16.000           |13.000          |18.000          |12.000         |22.000         |14.000          |16.000         |7.000           |4.500           |16.500         |14.41347550037811   |5.9256892426113605  |6.046657671805144   |2.484202890264803   |5.664976081149858   |6.3187369782259495  |8.432013460615442  |3.183289650660147   |5.568899711792268  |5.055553481074055   |4.692988173861085   |3.285110957030219   |2.5928727311613273  |3.9258940383051604  |3          |13         |3          |15.000               |16.157895          |17.000                |15.545455           |0                   |19.0            |78.413793       |26.137931     |57.241379     |6.103448       |17.724138      |20.034483     |26.620690     |14.758621    |26.931034    |14.586207     |15.103448    |6.413793      |4.379310      |18.482759    |75.000            |25.000          |57.000          |6.000            |18.000           |19.000          |25.000          |14.000         |27.000         |14.000          |15.000         |7.000           |5.000           |18.000         |11.977709171623763  |4.525516103164367   |6.743542763266205   |2.1438421117237154  |3.272139514140557   |6.721409078459665   |8.796971069635276  |4.23973690221457    |5.324679990384398   |4.127583554575243   |4.730937856281775   |3.235045131060771   |1.801066906030978   |4.3803187098657554  |1          |16         |7          |11.500               |15.666667          |10.000                |12.600000           |0                   |24.0            |
|0.0           |0.0           |0.0             |0.0             |0.0                |0.0               |0.0                 |0.0               |0.0                  |0.0                |0.0           |0.0            |1.0               |0.0           |0.0            |0.0           |0.0            |0.0                |0.0           |0.0           |0.0           |0.0           |0.0               |0.0                  |0.0               |0.0           |0.0                |0.0                 |0.0              |0.0                |0.0            |0.0           |0.0           |0.0           |0.0           |0.0             |0.0             |0.0                |0.0               |0.0                 |0.0               |0.0                  |0.0                |0.0           |1.0            |0.0               |0.0           |0.0            |0.0           |0.0            |0.0                |0.0           |0.0           |0.0           |0.0           |0.0               |0.0                  |0.0               |0.0           |0.0                |0.0                 |0.0              |0.0                |0.0            |0.0           |0.0           |2003      |1139        |1257        |79         |71         |2        |W           |12        |W           |4         |68.586207       |24.068966     |50.655172     |8.482759       |21.862069      |11.965517     |16.551724     |7.827586     |20.379310    |12.965517     |10.413793    |6.344828      |1.862069      |16.068966    |68.000            |23.000          |50.000          |9.000            |21.000           |11.000          |15.000          |7.000          |21.000         |13.000          |10.000         |6.000           |2.000           |16.000         |7.798888382327317   |3.261584124317507   |5.595124574127014   |2.5721127502502688  |4.680690867810007   |5.30823322773218    |6.299581652776634  |2.8418928551231484  |4.246122584193725  |3.6886191183151453  |4.187713696039881   |2.8694929865744574  |1.432384026719092   |4.415322638267786   |3          |11         |10         |12.000               |11.500000          |10.000                |10.800000           |0                   |24.0            |81.833333       |27.966667     |60.833333     |8.433333       |23.400000      |17.466667     |25.100000     |13.200000    |25.100000    |16.600000     |13.366667    |7.200000      |4.733333      |22.666667    |81.000            |28.000          |62.000          |9.000            |24.000           |18.000          |25.500          |13.500         |25.000         |16.000          |12.000         |6.500           |4.500           |22.000         |10.90739492271184   |5.549049828574258   |6.8485253157157855  |2.686920170008778   |4.132295003989913   |6.916912461496097   |8.968719585314282  |3.836305644757727   |4.4049345057560165  |4.445842664782459   |4.398144836178091   |3.6045947067596935  |2.6901267628124885  |5.351978886355962   |0          |16         |8          |18.000               |18.333333          |4.000                 |6.500000            |1                   |24.0            |

In [54]:
parameters = {
    "n_estimators": [100, 200, 300, 400, 500],
    # "learning_rate": [0.1, 0.2, 0.3, 0.4, 0.5],
    # "max_depth": list(range(3, 6, 1)),
    # "min_child_weight": list(range(1, 6, 1)),
}

In [55]:
def add_losing_matches(df):
    lose_rename = {
        "W_TEAMID": "L_TEAMID", 
        "W_SCORE" : "L_SCORE", 
        "L_TEAMID" : "W_TEAMID",
        "L_SCORE": "W_SCORE",
    }
    lose_rename.update({c : "L_" + c[2:] for c in df.columns if c.startswith('W_')})
    lose_rename.update({c : "W_" + c[2:] for c in df.columns if c.startswith('L_')})
    
    win_df = df.copy()
    lose_df = df.copy()
    
    lose_df = lose_df.rename(columns=lose_rename)
    
    return pd.concat([win_df, lose_df], axis=0, sort=False)

In [56]:
train = final.filter(F.col('SEASON') <= 2021)
test = final.filter(F.col('SEASON') > 2021)

In [57]:
df_pd = train.to_pandas()
train_2 = add_losing_matches(df_pd)
train_2 = session.create_dataframe(train_2)

In [58]:
train_2 = train_2.withColumn(
    "WIN_INDICATOR", F.when(train_2["W_SCORE"] > train_2["L_SCORE"], 1).otherwise(0)
)

In [72]:
test = test.withColumn(
    "WIN_INDICATOR", F.lit(1))

In [60]:
session.use_warehouse('MM_L')

In [67]:
train_2 = train_2.with_columns(
    ["W_WLOCN", "W_WLOCH", "W_WLOCA", "L_WLOCN", "L_WLOCH", "L_WLOCA"],
    [
        F.col("W_WLOCN").cast(T.LongType()),
        F.col("W_WLOCH").cast(T.LongType()),
        F.col("W_WLOCA").cast(T.LongType()),
        F.col("L_WLOCN").cast(T.LongType()),
        F.col("L_WLOCH").cast(T.LongType()),
        F.col("L_WLOCA").cast(T.LongType()),
    ],
)

In [68]:
all_rounds = GridSearchCV(
    estimator=XGBClassifier(),
    param_grid=parameters,
    n_jobs=-1,
    scoring="accuracy",
    input_cols=train_2.drop(['SEASON','WIN_INDICATOR','l_teamid','w_teamid','w_score','l_score','round','l_region','w_region']).columns,
    label_cols="WIN_INDICATOR",
    output_cols="PRED_WIN_INDICATOR",
)

# Train
all_rounds.fit(train_2)

The version of package 'snowflake-snowpark-python' in the local environment is 1.13.0, which does not fit the criteria for the requirement 'snowflake-snowpark-python<2'. Your UDF might not work when the package version is different between the server and your local environment.
Package 'fastparquet' is not installed in the local environment. Your UDF might not work when the package is installed on the server but not on your local environment.
The version of package 'pyarrow' in the local environment is 15.0.1, which does not fit the criteria for the requirement 'pyarrow<14'. Your UDF might not work when the package version is different between the server and your local environment.
The version of package 'cachetools' in the local environment is 5.3.3, which does not fit the criteria for the requirement 'cachetools<6'. Your UDF might not work when the package version is different between the server and your local environment.

In [ ]:
#session.use_warehouse('wh_xs')

In [74]:
result = all_rounds.predict(test).filter(F.col("ROUND") == 1)
result.count()

64

In [75]:
result = all_rounds.predict(test).filter(F.col("ROUND") == 1)

accuracy_2022 = accuracy_score(
    df=result.filter(result.season == 2022),
    y_true_col_names="WIN_INDICATOR",
    y_pred_col_names="PRED_WIN_INDICATOR",
)
print(f"Accuracy 2022: {accuracy_2022}")

accuracy_2023 = accuracy_score(
    df=result.filter(result.season == 2023),
    y_true_col_names="WIN_INDICATOR",
    y_pred_col_names="PRED_WIN_INDICATOR",
)
print(f"Accuracy 2023: {accuracy_2023}")

accuracy = accuracy_score(
    df=result, y_true_col_names="WIN_INDICATOR", y_pred_col_names="PRED_WIN_INDICATOR"
)

print(f"Accuracy total: {accuracy}")

Accuracy 2022: 0.8125
Accuracy 2023: 0.6875
Accuracy total: 0.75

#### Register Models that are good

In [77]:
optimal_model = all_rounds.to_sklearn().best_estimator_

def check_and_update(df, model_name):
    if df.empty:
        return "V_1"
    elif df[df["name"] == model_name].empty:
        return "V_1"
    else:
        # Increment model_version if df is not a pandas Series
        lst = sorted(ast.literal_eval(df["versions"][0]))
        last_value = lst[-1]
        prefix, num = last_value.rsplit("_", 1)
        new_last_value = f"{prefix}_{int(num)+1}"
        lst[-1] = new_last_value
        return new_last_value
# Get sample input data to pass into the registry logging function
X = train_2.drop(['SEASON','WIN_INDICATOR','l_teamid','w_teamid','w_score','l_score','round','l_region','w_region']).limit(100)

# Create a registry and log the model
# You can specify a different DB and Schema if you'd like
# otherwise it uses the session context
reg = Registry(session=session)

reg_df = reg.show_models()

# Define model name and version (use uppercase for name)
model_name = "MARCHMADNESS"

model_version = check_and_update(reg_df, model_name)

mm_model = reg.log_model(
    model_name=model_name,
    version_name=model_version,
    model=optimal_model,
    sample_input_data=X,
)

# Add evaluation metric
mm_model.set_metric(
    metric_name="accuracy_2023",
    value= accuracy_2023
)

mm_model.set_metric(
    metric_name="accuracy_2022",
    value= accuracy_2022,
)
reg.get_model(model_name).show_versions()

,created_on,name,comment,database_name,schema_name,module_name,is_default_version,functions,metadata,user_data
0,2024-03-20 14:41:44.382000-07:00,V_1,None,MARCHMADNESS,MEN,MARCHMADNESS,true,"[""PREDICT_PROBA"",""PREDICT"",""APPLY""]","{""metrics"": {""accuracy_2023"": 0.6875, ""accurac...","{""snowpark_ml_data"":{""functions"":[{""name"":""APP..."

# Predicting the Bracket & final four (we want as many final 4 as possible)

## Results play in games

In [79]:
result = all_rounds.predict(test).filter(F.col('ROUND') == 0).filter(F.col("season") == 2023)

teams = session.table('m_teams')

result = result.select('season','l_teamID','l_seed','l_region','w_teamid','w_seed','w_region','win_indicator','pred_win_indicator')

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

res_teams = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select('season','l_teamid','w_teamid','L_TEAM_NAME','l_seed','l_region','W_TEAM_NAME','w_seed','w_region','WIN_INDICATOR','PRED_WIN_INDICATOR')
)

res_teams.sort(F.col("w_team_name")).show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
|"SEASON"  |"L_TEAMID"  |"W_TEAMID"  |"L_TEAM_NAME"   |"L_SEED"  |"L_REGION"  |"W_TEAM_NAME"   |"W_SEED"  |"W_REGION"  |"WIN_INDICATOR"  |"PRED_WIN_INDICATOR"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
|2023      |1305        |1113        |Nevada          |11        |Z           |Arizona St      |11        |Z           |1                |1.0                   |
|2023      |1411        |1192        |TX Southern     |16        |W           |F Dickinson     |16        |W           |1                |1.0                   |
|2023      |1280        |1338        |Mississippi St  |11        |Y           |Pittsburgh      |11        |Y           |1                |1.0                   |
|2023      |1369        |1394        |SE Missouri St  |16        |X           |TAM C. Christi  |16        |X           |1                |1.0                   |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

## Results round 1

In [80]:
result = all_rounds.predict(test.filter(F.col('ROUND') == 1)).filter(F.col("season") == 2023)

teams = session.table('m_teams')

result = result.select('season','l_teamID','l_seed','l_region','w_teamid','w_seed','w_region','win_indicator','pred_win_indicator')

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

res_teams = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select('season','l_teamid','w_teamid','L_TEAM_NAME','l_seed','l_region','W_TEAM_NAME','w_seed','w_region','WIN_INDICATOR','PRED_WIN_INDICATOR')
)

print('The round of 32')
res_teams.count()

The round of 32

32

In [81]:
result = all_rounds.predict(test.filter(F.col("ROUND") == 1)).filter(F.col("season") == 2023)

teams = session.table("m_teams")
for col in teams.columns:
    teams = teams.withColumnRenamed(col, col.upper())

result = (
    result.select(
        "season",
        "l_teamID",
        "l_seed",
        "w_seed",
        "l_region",
        "w_teamid",
        "w_region",
        "win_indicator",
        "pred_win_indicator",
    )
)

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

round_1_results = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select(
        "season",
        "l_teamid",
        "w_teamid",
        "L_TEAM_NAME",
        "l_seed",
        "w_seed",
        "l_region",
        "W_TEAM_NAME",
        "w_region",
        "WIN_INDICATOR",
        "PRED_WIN_INDICATOR",
    )
)

In [82]:
round_1_results.sort('W_REGION').show(32)

------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"SEASON"  |"L_TEAMID"  |"W_TEAMID"  |"L_TEAM_NAME"     |"L_SEED"  |"W_SEED"  |"L_REGION"  |"W_TEAM_NAME"  |"W_REGION"  |"WIN_INDICATOR"  |"PRED_WIN_INDICATOR"  |
------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2023      |1272        |1194        |Memphis           |8         |9         |W           |FL Atlantic    |W           |1                |1.0                   |
|2023      |1418        |1397        |Louisiana         |13        |4         |W           |Tennessee      |W           |1                |1.0                   |
|2023      |1344        |1246        |Providence        |11        |6         |W           |Kentucky       |W           |1                |1.0                   |
|2023      |1331        |1181        |Oral Roberts      |12        |5         |W           |Duke           |W           |1                |0.0                   |
|2023      |1425        |1277        |USC               |10        |7         |W           |Michigan St    |W           |1                |0.0                   |
|2023      |1436        |1266        |Vermont           |15        |2         |W           |Marquette      |W           |1                |1.0                   |
|2023      |1345        |1192        |Purdue            |1         |16        |W           |F Dickinson    |W           |1                |0.0                   |
|2023      |1286        |1243        |Montana St        |14        |3         |W           |Kansas St      |W           |1                |1.0                   |
|2023      |1112        |1343        |Arizona           |2         |15        |X           |Princeton      |X           |1                |0.0                   |
|2023      |1364        |1124        |UC Santa Barbara  |14        |3         |X           |Baylor         |X           |1                |1.0                   |
|2023      |1452        |1268        |West Virginia     |9         |8         |X           |Maryland       |X           |1                |1.0                   |
|2023      |1438        |1202        |Virginia          |4         |13        |X           |Furman         |X           |1                |0.0                   |
|2023      |1394        |1104        |TAM C. Christi    |16        |1         |X           |Alabama        |X           |1                |1.0                   |
|2023      |1158        |1361        |Col Charleston    |12        |5         |X           |San Diego St   |X           |1                |0.0                   |
|2023      |1301        |1166        |NC State          |11        |6         |X           |Creighton      |X           |1                |1.0                   |
|2023      |1429        |1281        |Utah St           |10        |7         |X           |Missouri       |X           |1                |1.0                   |
|2023      |1401        |1336        |Texas A&M         |7         |10        |Y           |Penn St        |Y           |1                |1.0                   |
|2023      |1179        |1274        |Drake             |12        |5         |Y           |Miami FL       |Y           |1                |1.0                   |
|2023      |1245        |1231        |Kent              |13        |4         |Y           |Indiana        |Y           |1                |0.0                   |
|2023      |1234        |1120        |Iowa              |8         |9         |Y           |Auburn         |Y           |1                |0.0                   |
|2023      |1297        |1222        |N Kentucky        |16        |1         |Y           |Houston        |Y           |1                |1.0                   |
|2023      |1235        |1338        |Iowa St           |6         |11        |Y           |Pittsburgh     |Y           |1                |0.0                   |
|2023      |1159        |1400        |Colgate           |15        |2         |Y           |Texas          |Y           |1                |1.0                   |
|2023      |1244        |1462        |Kennesaw          |14        |3         |Y           |Xavier         |Y           |1                |1.0                   |
|2023      |1228        |1116        |Illinois          |9         |8         |Z           |Arkansas       |Z           |1                |0.0                   |
|2023      |1233        |1163        |Iona              |13        |4         |Z           |Connecticut    |Z           |1                |1.0                   |
|2023      |1421        |1417        |UNC Asheville     |15        |2         |Z           |UCLA           |Z           |1                |1.0                   |
|2023      |1224        |1242        |Howard            |16        |1         |Z           |Kansas         |Z           |1                |1.0                   |
|2023      |1113        |1395        |Arizona St        |11        |6         |Z           |TCU            |Z           |1                |1.0                   |
|2023      |1433        |1388        |VCU               |12        |5         |Z           |St Mary's CA   |Z           |1                |1.0                   |
|2023      |1213        |1211        |Grand Canyon      |14        |3         |Z           |Gonzaga        |Z           |1                |1.0                   |
|2023      |1129        |1321        |Boise St          |10        |7         |Z           |Northwestern   |Z           |1                |1.0                   |
------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [83]:
round_1_winners = round_1_results.with_column(
    "W_TEAM_ID",
    when((round_1_results.PRED_WIN_INDICATOR == 1), round_1_results.w_teamid)
    .otherwise(round_1_results.l_teamID),
).with_column(
    "W_TEAM_NAME",
    when((round_1_results.PRED_WIN_INDICATOR == 1), round_1_results.w_team_name)
    .otherwise(round_1_results.l_team_name),
).with_column(
    "W_SEED",
    when((round_1_results.PRED_WIN_INDICATOR == 1), round_1_results.w_seed)
    .otherwise(round_1_results.l_seed),
).with_column(
    "W_REGION",
    when((round_1_results.PRED_WIN_INDICATOR == 1), round_1_results.w_region)
    .otherwise(round_1_results.l_region)
).select("W_TEAM_ID","W_TEAM_NAME","W_SEED","W_REGION")

# Winners round 1

In [84]:
round_1_winners.sort('W_REGION').show(32)

--------------------------------------------------------
|"W_TEAM_ID"  |"W_TEAM_NAME"   |"W_SEED"  |"W_REGION"  |
--------------------------------------------------------
|1194         |FL Atlantic     |9         |W           |
|1397         |Tennessee       |4         |W           |
|1246         |Kentucky        |6         |W           |
|1331         |Oral Roberts    |12        |W           |
|1425         |USC             |10        |W           |
|1266         |Marquette       |2         |W           |
|1345         |Purdue          |1         |W           |
|1243         |Kansas St       |3         |W           |
|1112         |Arizona         |2         |X           |
|1124         |Baylor          |3         |X           |
|1268         |Maryland        |8         |X           |
|1438         |Virginia        |4         |X           |
|1104         |Alabama         |1         |X           |
|1158         |Col Charleston  |12        |X           |
|1166         |Creighton       |6         |X           |
|1281         |Missouri        |7         |X           |
|1336         |Penn St         |10        |Y           |
|1274         |Miami FL        |5         |Y           |
|1245         |Kent            |13        |Y           |
|1234         |Iowa            |8         |Y           |
|1222         |Houston         |1         |Y           |
|1235         |Iowa St         |6         |Y           |
|1400         |Texas           |2         |Y           |
|1462         |Xavier          |3         |Y           |
|1228         |Illinois        |9         |Z           |
|1163         |Connecticut     |4         |Z           |
|1417         |UCLA            |2         |Z           |
|1242         |Kansas          |1         |Z           |
|1395         |TCU             |6         |Z           |
|1388         |St Mary's CA    |5         |Z           |
|1211         |Gonzaga         |3         |Z           |
|1321         |Northwestern    |7         |Z           |
--------------------------------------------------------

In [85]:
df1 = round_1_winners.cache_result()
df2 = round_1_winners.cache_result()

second_round_matchups = df1.join(
    df2,
    (df1.w_region == df2.w_region)
    & (
        (df1.w_seed == 1) & (df2.w_seed == 8)
        | (df1.w_seed == 1) & (df2.w_seed == 9)
        | (df1.w_seed == 16) & (df2.w_seed == 8)
        | (df1.w_seed == 16) & (df2.w_seed == 9)
        | (df1.w_seed == 4) & (df2.w_seed == 5)
        | (df1.w_seed == 4) & (df2.w_seed == 12)
        | (df1.w_seed == 13) & (df2.w_seed == 5)
        | (df1.w_seed == 13) & (df2.w_seed == 12)
        | (df1.w_seed == 3) & (df2.w_seed == 6)
        | (df1.w_seed == 3) & (df2.w_seed == 11)
        | (df1.w_seed == 14) & (df2.w_seed == 6)
        | (df1.w_seed == 14) & (df2.w_seed == 11)
        | (df1.w_seed == 2) & (df2.w_seed == 7)
        | (df1.w_seed == 2) & (df2.w_seed == 10)
        | (df1.w_seed == 15) & (df2.w_seed == 7)
        | (df1.w_seed == 15) & (df2.w_seed == 10)
    ),
    "inner",
).select(
    (df1.W_TEAM_NAME).alias("W_team_name"),
    (df1.W_REGION).alias("w_region"),
    (df1.W_TEAM_ID).alias("WTeamID2"),
    (df1.W_SEED).alias("w_seed"),
    (df2.W_TEAM_NAME).alias("l_Team_name"),
    (df2.W_REGION).alias("l_region"),
    (df2.W_TEAM_ID).alias("lteamID2"),
    (df2.W_SEED).alias("l_seed"),
)

second_round_matchups.sort('W_REGION').show(16)

------------------------------------------------------------------------------------------------------------
|"W_TEAM_NAME"  |"W_REGION"  |"WTEAMID2"  |"W_SEED"  |"L_TEAM_NAME"   |"L_REGION"  |"LTEAMID2"  |"L_SEED"  |
------------------------------------------------------------------------------------------------------------
|Kansas St      |W           |1243        |3         |Kentucky        |W           |1246        |6         |
|Purdue         |W           |1345        |1         |FL Atlantic     |W           |1194        |9         |
|Tennessee      |W           |1397        |4         |Oral Roberts    |W           |1331        |12        |
|Marquette      |W           |1266        |2         |USC             |W           |1425        |10        |
|Alabama        |X           |1104        |1         |Maryland        |X           |1268        |8         |
|Virginia       |X           |1438        |4         |Col Charleston  |X           |1158        |12        |
|Arizona        |X           |1112        |2         |Missouri        |X           |1281        |7         |
|Baylor         |X           |1124        |3         |Creighton       |X           |1166        |6         |
|Houston        |Y           |1222        |1         |Iowa            |Y           |1234        |8         |
|Xavier         |Y           |1462        |3         |Iowa St         |Y           |1235        |6         |
|Texas          |Y           |1400        |2         |Penn St         |Y           |1336        |10        |
|Kent           |Y           |1245        |13        |Miami FL        |Y           |1274        |5         |
|Kansas         |Z           |1242        |1         |Illinois        |Z           |1228        |9         |
|Connecticut    |Z           |1163        |4         |St Mary's CA    |Z           |1388        |5         |
|UCLA           |Z           |1417        |2         |Northwestern    |Z           |1321        |7         |
|Gonzaga        |Z           |1211        |3         |TCU             |Z           |1395        |6         |
------------------------------------------------------------------------------------------------------------

# ROUND OF 32!!!

In [86]:
second_round_matchups.select(
    F.col("W_TEAM_NAME").alias("TEAM_1"),
    F.col("L_TEAM_NAME").alias("TEAM_2"),
    F.col("W_SEED").alias("SEED_1"),
    F.col("L_SEED").alias("SEED_2"),
    F.col("W_REGION").alias("REGION"),
).sort("REGION").show(20)

-----------------------------------------------------------------
|"TEAM_1"     |"TEAM_2"        |"SEED_1"  |"SEED_2"  |"REGION"  |
-----------------------------------------------------------------
|Kansas St    |Kentucky        |3         |6         |W         |
|Purdue       |FL Atlantic     |1         |9         |W         |
|Tennessee    |Oral Roberts    |4         |12        |W         |
|Marquette    |USC             |2         |10        |W         |
|Alabama      |Maryland        |1         |8         |X         |
|Virginia     |Col Charleston  |4         |12        |X         |
|Arizona      |Missouri        |2         |7         |X         |
|Baylor       |Creighton       |3         |6         |X         |
|Houston      |Iowa            |1         |8         |Y         |
|Xavier       |Iowa St         |3         |6         |Y         |
|Texas        |Penn St         |2         |10        |Y         |
|Kent         |Miami FL        |13        |5         |Y         |
|Kansas       |Illinois        |1         |9         |Z         |
|Connecticut  |St Mary's CA    |4         |5         |Z         |
|UCLA         |Northwestern    |2         |7         |Z         |
|Gonzaga      |TCU             |3         |6         |Z         |
-----------------------------------------------------------------

In [90]:
session.table('FINAL_SEASON_STATS').show()

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"SEASON"  |"TEAMID"  |"SCORE_MEAN"  |"FGM_MEAN"  |"FGA_MEAN"  |"FGM3_MEAN"  |"FGA3_MEAN"  |"FTM_MEAN"  |"FTA_MEAN"  |"OR_MEAN"  |"DR_MEAN"  |"AST_MEAN"  |"TO_MEAN"  |"STL_MEAN"  |"BLK_MEAN"  |"PF_MEAN"  |"SCORE_MEDIAN"  |"FGM_MEDIAN"  |"FGA_MEDIAN"  |"FGM3_MEDIAN"  |"FGA3_MEDIAN"  |"FTM_MEDIAN"  |"FTA_MEDIAN"  |"OR_MEDIAN"  |"DR_MEDIAN"  |"AST_MEDIAN"  |"TO_MEDIAN"  |"STL_MEDIAN"  |"BLK_MEDIAN"  |"PF_MEDIAN"  |"SCORE_STDDEV"      |"FGM_STDDEV"        |"FGA_STDDEV"        |"FGM3_STDDEV"       |"FGA3_STDDEV"       |"FTM_STDDEV"        |"FTA_STDDEV"       |"OR_STDDEV"         |"DR_STDDEV"         |"AST_STDDEV"        |"TO_STDDEV"         |"STL_STDDEV"        |"BLK_STDDEV"        |"PF_STDDEV"         |"WLOCN"  |"WLOCH"  |"WLOCA"  |"WINMARGINMEDIAN"  |"WINMARGINMEAN"  |"LOSEMARGINMEDIAN"  |"LOSEMARGINMEAN"  |"WON_CONFERENCE"  |"TOTAL_WINS"  |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2020      |1112      |76.406250     |26.562500   |59.531250   |7.281250     |20.656250    |16.000000   |21.843750   |10.906250  |26.531250  |15.375000   |11.875000  |6.750000    |3.718750    |18.625000  |75.000          |26.500        |58.000        |7.500          |21.000         |15.000        |21.500        |11.000       |26.000       |16.000        |12.000       |6.000         |3.000         |18.500       |13.492792298112352  |6.236921836932061   |6.058767944062555   |3.1339388953838907  |4.092553237283542   |5.736133366650395   |7.002807651221045  |3.051804056619625   |5.500641417144005   |5.320380813438076   |3.553734936654674   |2.7591489629956554  |1.818088006670744   |3.357706657824653   |4        |13       |4        |17.000             |20.000000        |5.000               |5.909091          |1                 |21.0          |
|2014      |1257      |82.117647     |28.911765   |61.029412   |8.058824     |21.705882    |16.235294   |24.647059   |13.705882  |24.176471  |15.676471   |10.294118  |10.117647   |4.617647    |19.500000  |83.500          |28.000        |61.000        |7.500          |21.500         |16.000        |23.500        |13.500       |23.500       |16.000        |10.000       |10.000        |4.000         |19.000       |12.099999256198325  |4.782338967492789   |6.575829453384569   |3.8842430407995843  |5.697045550107529   |6.795982857541652   |7.507097042132864  |3.6641540633548693  |4.648040232183883   |4.623527333108349   |3.119143311872669   |3.6495305177515642  |1.7755016192614412  |4.265790665281174   |4        |16       |9        |26.000             |25.862069        |6.000               |6.200000          |1                 |29.0          |
|2020      |1170      |62.392857     |22.392857   |54.678571   |4.892857     |15.500000    |12.714286   |17.571429   |11.000000  |22.678571  |12.214286   |12.321429  |6.964286    |3.892857    |18.035714  |62.500          |22.000        |54.000        |5.000          |15.000         |11.500        |18.000        |10.000       |23.000       |12.000        |12.000       |6.000         |3.000         |19.000       |9.19878932251413    |3.8905324828357366  |4.891819089050617   |2.657474176732485   |5.3644923338560195  |5.449139565105669   |7.350628952681532  |3.091206237053749   |4.018969519665458   |4.771498297180876   |3.1038037953453177  |2.5601236298272783  |2.298780546289706   |4.24684753670296    |2        |8        |4        |10.500             |10.714286        |6.500               |9.357143          |1                 |14.0          |
|2016      |1332      |78.545455     |27.303030   |58.878788   |7.000000     |19.969697    |16.939394   |23.696970   |11.757576  |24.000000  |13.636364   |11.363636  |7.606061    |5.818182    |18.030303  |77.000          |27.000        |59.000        |7.000          |21.000         |16.000        |22.000        |12.000       |24.000       |14.000        |11.000       |8.000         |6.000         |19.000       |9.209678713179954   |3.661325306497635   |5.206711822254041   |2.2638462845343543  |4.149434057796316   |5.66755785149124    |7.451865739531275  |3.1526804468578797  |4.227883631321941   |3.533926428209846   |3.2192601634537086  |2.8166845758799477  |2.9203439865878815  |3.2738055837205726  |5        |17       |5        |13.000             |13.185185        |7.500               |9.000000          |1                 |27.0          |
|2015      |1352      |69.000000     |24.303030   |54.484848   |6.393939     |16.818182    |14.000000   |19.606061   |10.424242  |23.000000  |12.242424   |13.757576  |8.545455    |2.939394    |18.545455  |68.000          |24.000        |55.000        |6.000          |16.000         |13.000        |18.000        |10.000       |23.000       |11.000        |13.000       |8.000         |3.000         |18.000       |11.299889379989523  |4.857242324611775   |6.978185724097632   |2.7034629644217434  |5.071085583975092   |5.963430220938282   |8.069771496145352  |3.7751680757285495  |4.616546328154847   |4.394814444319578   |4.272223542840426   |3.052569737123134   |1.869816033731661   |4.6239249561384534  |1        |10       |8        |12.000             |11.842105        |7.500               |13.071429         |1                 |19.0          |
|2021      |1180      |71.473684     |26.052632   |54.631579   |7.263158     |19.526316    |12.105263   |15.578947   |7.526316   |23.631579  |15.157895   |11.789474  |4.684211    |2.368421    |4.684211   |73.000          |26.000        |55.000        |7.000          |18.000         |11.000        |15.000        |8.000        |24.000       |15.000        |12.000       |5.000         |2.000         |0.000        |9.453796538957246   |4.478016525203988   |5.2726814809923805  |2.468515140727316   |4.2212217425764305  |4.306258236566869   |4.947679456068268  |2.037657233196987   |3.5933662490762055  |3.685755689136218   |3.5210312409860833  |2.4956101458360838  |1.949658944533633   |7.965569157317009   |5        |3        |4        |9.500              |11.000000        |5.000               |6.285714          |1                 |12.0          |
|2013      |1307      |67.441176     |21.970588   |51.735294   |6.411765     |18.088235    |17.088235   |23.676471   |9.382353   |25.852941  |14.617647   |11.500000  |6.117647    |3.911765    |15.441176  |67.000          |21.500        |52.000        |6.000          |19.000         |17.000        |23.000        |9.000        |26.000       |14.500        |11.000       |6.000         |4.000         |15.000       |11.801877562489793  |4.635078963728666   |5.298992640115666   |3.144187971480077   |4.679857903825713   |7.629161159655759   |8.664523933835026  |3.312187796608157   |4.120402650227281   |4.31357763347317    |3.799920262321303   |2.293134753999424   |2.2206694936437525  |3.9862731968594427  |5        |15       |9        |9.000              |9.965517         |9.000               |10.000000         |1                 |29.0          |
|2010      |1288      |76.750000     |26.166667   |60.500000   |5.611111     |16.611111    |18.805556   |26.750000   |15.416667  |24.861111  |12.722222   |13.527778  |6.583333    |4.027778    |21.111111  |74.000          |25.000        |60.500        |5.500          |17.000         |19.000        |25.000        |14.500       |25.500       |12.000        |13.500       |6.000         |3.000         |20.000       |11.43522129213073   |5.654328342075653   |9.76436669733373    |2.4175284900079257  |4.0797602870757     |7.078415641935701   |8.974169265174353  |5.357904721064009   |3.96522584476597    |3.8590235811666145  |4.09519657647835    |2.394935072188806   |2.535306293133041   |4.640060236677968   |4        |11       |12       |10.000             |12.259259        |9.000               |10.777778         |1                 |27.0          |
|2013      |1322      |77.962963     |27.444444   |61.481481   |5.740741     |18.259259    |17.333333   |25.111111   |13.666667  |24.481481  |14.629630   |14.000000  |9.333333    |4.518519    |19.888889  |78.000          |28.000        |62.000        |6.000          |18.000         |16.000        |24.000        |13.000       |25.000       |14.000        |14.000       |8.000         |4.000         |19.000       |12.506864195312907  |5.176376338714178   |6.553744502191095   |3.033056214447731   |4.024851550057468   |5.2109352327581275  |7.186169076775191  |3.9807227986887006  |5.131878993117433   |4.8765384239232645  |4.640954858647087   |4.251696484933984   |2.225211675324395   |5.010245902148916   |2        |9        |8        |11.000             |12.052632        |10.000              |10.000000         |1                 |19.0          |
|2017      |1190      |79.593750     |27.531250   |55.718750   |7.500000     |19.625000    |17.031250   |24.406250   |9.593750   |26.156250  |14.843750   |14.937500  |8.593750    |4.875000    |20.343750  |78.500          |26.500        |55.000        |7.000          |18.500         |16.000        |24.500        |9.500        |25.000       |15.000        |15.000       |9.000         |5.000         |20.000       |13.78605977065238   |5.327859701606265   |7.561508513517657   |3.1622776601683795  |5.801835054532316   |5.5269683371627885  |6.941503871640496  |3.434731284977036   |4.515988596088347   |4.436719058042779   |3.5097789104158683  |3.4720950447820407  |2.1664597849948657  |2.3909692595263534  |6        |11       |8        |12.000             |15.160000        |6.000               |7.571429          |1                 |25.0          |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [93]:
second_round = second_round_matchups.select('WTEAMID2','LTEAMID2','W_SEED','L_SEED')

season = (
    session.table("FINAL_SEASON_STATS").filter(F.col("season") == 2023).drop("W_SEASON")
)

season_w = season.select(*[F.col(col).alias(f"W_{col}") for col in season.columns])

season_l = season.select(*[F.col(col).alias(f"L_{col}") for col in season.columns])

df1 = second_round.join(season_w, season_w.w_teamid == second_round.wTEAMID2)

df2 = df1.join(season_l, season_l.l_teamid == second_round.lTEAMID2)

games_32 = df2.drop('WTEAMID2','lTEAMID2')

games_32.count()

16

In [94]:
result = all_rounds.predict(games_32)

teams = session.table("m_teams")

result = (
    result.select(
        "l_teamID",
        "l_seed",
        "w_seed",
        "l_region",
        "w_teamid",
        "w_region",
        "pred_win_indicator",
    )
)

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

round_2_results = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select(
        "l_teamid",
        "w_teamid",
        "L_TEAM_NAME",
        "l_seed",
        "w_seed",
        "l_region",
        "W_TEAM_NAME",
        "w_region",
        "PRED_WIN_INDICATOR",
    )
)

In [95]:
round_2_winners = round_2_results.with_column(
    "W_TEAM_ID",
    when((round_2_results.PRED_WIN_INDICATOR == 1), round_2_results.w_teamid)
    .otherwise(round_2_results.l_teamID),
).with_column(
    "W_TEAM_NAME",
    when((round_2_results.PRED_WIN_INDICATOR == 1), round_2_results.w_team_name)
    .otherwise(round_2_results.l_team_name),
).with_column(
    "W_SEED",
    when((round_2_results.PRED_WIN_INDICATOR == 1), round_2_results.w_seed)
    .otherwise(round_2_results.l_seed),
).with_column(
    "W_REGION",
    when((round_2_results.PRED_WIN_INDICATOR == 1), round_2_results.w_region)
    .otherwise(round_2_results.l_region)
).select("W_TEAM_ID","W_TEAM_NAME","W_SEED","W_REGION")

# Round 2 winners

In [96]:
round_2_winners.sort('W_REGION').show(20)

-------------------------------------------------------
|"W_TEAM_ID"  |"W_TEAM_NAME"  |"W_SEED"  |"W_REGION"  |
-------------------------------------------------------
|1397         |Tennessee      |4         |W           |
|1266         |Marquette      |2         |W           |
|1246         |Kentucky       |6         |W           |
|1345         |Purdue         |1         |W           |
|1438         |Virginia       |4         |X           |
|1112         |Arizona        |2         |X           |
|1104         |Alabama        |1         |X           |
|1124         |Baylor         |3         |X           |
|1245         |Kent           |13        |Y           |
|1400         |Texas          |2         |Y           |
|1222         |Houston        |1         |Y           |
|1235         |Iowa St        |6         |Y           |
|1388         |St Mary's CA   |5         |Z           |
|1242         |Kansas         |1         |Z           |
|1417         |UCLA           |2         |Z           |
|1211         |Gonzaga        |3         |Z           |
-------------------------------------------------------

In [97]:
df1 = round_2_winners.cache_result()
df2 = round_2_winners.cache_result()

third_round_matchups = df1.join(
    df2,
    (df1.w_region == df2.w_region)
    & (
        (df1.w_seed == 1) & (df2.w_seed.isin([5, 12, 4, 13])) |
        (df1.w_seed == 16) & (df2.w_seed.isin([5, 12, 4, 13])) |
        (df1.w_seed == 8) & (df2.w_seed.isin([5, 12, 4, 13])) |
        (df1.w_seed == 9) & (df2.w_seed.isin([5, 12, 4, 13])) |
        (df1.w_seed == 6) & (df2.w_seed.isin([7,10,2,15])) |
        (df1.w_seed == 11) & (df2.w_seed.isin([7,10,2,15])) |
        (df1.w_seed == 3) & (df2.w_seed.isin([7,10,2,15]))|
        (df1.w_seed == 14) & (df2.w_seed.isin([7,10,2,15]))
    ),
    "inner",
).select(
    (df1.W_TEAM_NAME).alias("W_team_name"),
    (df1.W_REGION).alias("w_region"),
    (df1.W_TEAM_ID).alias("WTeamID2"),
    (df1.W_SEED).alias("w_seed"),
    (df2.W_TEAM_NAME).alias("l_Team_name"),
    (df2.W_REGION).alias("l_region"),
    (df2.W_TEAM_ID).alias("lteamID2"),
    (df2.W_SEED).alias("l_seed"),
)

third_round_matchups.sort("W_REGION").show(20)

-----------------------------------------------------------------------------------------------------------
|"W_TEAM_NAME"  |"W_REGION"  |"WTEAMID2"  |"W_SEED"  |"L_TEAM_NAME"  |"L_REGION"  |"LTEAMID2"  |"L_SEED"  |
-----------------------------------------------------------------------------------------------------------
|Kentucky       |W           |1246        |6         |Marquette      |W           |1266        |2         |
|Purdue         |W           |1345        |1         |Tennessee      |W           |1397        |4         |
|Alabama        |X           |1104        |1         |Virginia       |X           |1438        |4         |
|Baylor         |X           |1124        |3         |Arizona        |X           |1112        |2         |
|Houston        |Y           |1222        |1         |Kent           |Y           |1245        |13        |
|Iowa St        |Y           |1235        |6         |Texas          |Y           |1400        |2         |
|Kansas         |Z           |1242        |1         |St Mary's CA   |Z           |1388        |5         |
|Gonzaga        |Z           |1211        |3         |UCLA           |Z           |1417        |2         |
-----------------------------------------------------------------------------------------------------------

# SWEET SIXTEEN!!!

In [98]:
third_round_matchups.select(
    F.col("W_TEAM_NAME").alias("TEAM_1"),
    F.col("L_TEAM_NAME").alias("TEAM_2"),
    F.col("W_SEED").alias("SEED_1"),
    F.col("L_SEED").alias("SEED_2"),
    F.col("W_REGION").alias("REGION"),
).sort("REGION").show(20)

------------------------------------------------------------
|"TEAM_1"  |"TEAM_2"      |"SEED_1"  |"SEED_2"  |"REGION"  |
------------------------------------------------------------
|Kentucky  |Marquette     |6         |2         |W         |
|Purdue    |Tennessee     |1         |4         |W         |
|Alabama   |Virginia      |1         |4         |X         |
|Baylor    |Arizona       |3         |2         |X         |
|Houston   |Kent          |1         |13        |Y         |
|Iowa St   |Texas         |6         |2         |Y         |
|Kansas    |St Mary's CA  |1         |5         |Z         |
|Gonzaga   |UCLA          |3         |2         |Z         |
------------------------------------------------------------

In [99]:
third_round = third_round_matchups.select('WTEAMID2','LTEAMID2','W_SEED','L_SEED')

season = (
    session.table("FINAL_SEASON_STATS").filter(F.col("season") == 2023).drop("W_SEASON")
)

season_w = season.select(*[F.col(col).alias(f"W_{col}") for col in season.columns])

season_l = season.select(*[F.col(col).alias(f"L_{col}") for col in season.columns])

df1 = third_round.join(season_w, season_w.w_teamid == third_round.wTEAMID2)

df2 = df1.join(season_l, season_l.l_teamid == third_round.lTEAMID2)

games_16 = df2.drop('WTEAMID2','lTEAMID2')

games_16.count()

8

In [100]:
result = all_rounds.predict(games_16)

teams = session.table("m_teams")

result = (
    result.select(
        "l_teamID",
        "l_seed",
        "w_seed",
        "l_region",
        "w_teamid",
        "w_region",
        "pred_win_indicator",
    )
)

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

sweet_16_results = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select(
        "l_teamid",
        "w_teamid",
        "L_TEAM_NAME",
        "l_seed",
        "w_seed",
        "l_region",
        "W_TEAM_NAME",
        "w_region",
        "PRED_WIN_INDICATOR",
    )
)

In [101]:
sweet_16_winners = sweet_16_results.with_column(
    "W_TEAM_ID",
    when((sweet_16_results.PRED_WIN_INDICATOR == 1), sweet_16_results.w_teamid)
    .otherwise(sweet_16_results.l_teamID),
).with_column(
    "W_TEAM_NAME",
    when((sweet_16_results.PRED_WIN_INDICATOR == 1), sweet_16_results.w_team_name)
    .otherwise(sweet_16_results.l_team_name),
).with_column(
    "W_SEED",
    when((sweet_16_results.PRED_WIN_INDICATOR == 1), sweet_16_results.w_seed)
    .otherwise(sweet_16_results.l_seed),
).with_column(
    "W_REGION",
    when((sweet_16_results.PRED_WIN_INDICATOR == 1), sweet_16_results.w_region)
    .otherwise(sweet_16_results.l_region)
).select("W_TEAM_ID","W_TEAM_NAME","W_SEED","W_REGION")

# Sweet 16 winners!

In [102]:
sweet_16_winners.sort('W_REGION').show(20)

-------------------------------------------------------
|"W_TEAM_ID"  |"W_TEAM_NAME"  |"W_SEED"  |"W_REGION"  |
-------------------------------------------------------
|1266         |Marquette      |2         |W           |
|1345         |Purdue         |1         |W           |
|1124         |Baylor         |3         |X           |
|1104         |Alabama        |1         |X           |
|1222         |Houston        |1         |Y           |
|1400         |Texas          |2         |Y           |
|1211         |Gonzaga        |3         |Z           |
|1388         |St Mary's CA   |5         |Z           |
-------------------------------------------------------

In [103]:
df1 = sweet_16_winners.cache_result()
df2 = sweet_16_winners.cache_result()

elite_8_matchups = df1.join(
    df2,
    (df1.w_region == df2.w_region)
    & (
        (df1.w_seed == 1) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) |
        (df1.w_seed == 16) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) |
        (df1.w_seed == 8) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) |
        (df1.w_seed == 9) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) |
        (df1.w_seed == 5) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) |
        (df1.w_seed == 12) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) |
        (df1.w_seed == 4) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) |
        (df1.w_seed == 13) & (df2.w_seed.isin([6,11,3,14,7,10,2,15])) 
    ),
    "inner",
).select(
    (df1.W_TEAM_NAME).alias("W_team_name"),
    (df1.W_REGION).alias("w_region"),
    (df1.W_TEAM_ID).alias("WTeamID2"),
    (df1.W_SEED).alias("w_seed"),
    (df2.W_TEAM_NAME).alias("l_Team_name"),
    (df2.W_REGION).alias("l_region"),
    (df2.W_TEAM_ID).alias("lteamID2"),
    (df2.W_SEED).alias("l_seed"),
)

elite_8_matchups.sort("W_REGION").show(20)

-----------------------------------------------------------------------------------------------------------
|"W_TEAM_NAME"  |"W_REGION"  |"WTEAMID2"  |"W_SEED"  |"L_TEAM_NAME"  |"L_REGION"  |"LTEAMID2"  |"L_SEED"  |
-----------------------------------------------------------------------------------------------------------
|Purdue         |W           |1345        |1         |Marquette      |W           |1266        |2         |
|Alabama        |X           |1104        |1         |Baylor         |X           |1124        |3         |
|Houston        |Y           |1222        |1         |Texas          |Y           |1400        |2         |
|St Mary's CA   |Z           |1388        |5         |Gonzaga        |Z           |1211        |3         |
-----------------------------------------------------------------------------------------------------------

# Elite 8

In [104]:
elite_8_matchups.select(
    F.col("W_TEAM_NAME").alias("TEAM_1"),
    F.col("L_TEAM_NAME").alias("TEAM_2"),
    F.col("W_SEED").alias("SEED_1"),
    F.col("L_SEED").alias("SEED_2"),
    F.col("W_REGION").alias("REGION"),
).sort("REGION").show(20)

-------------------------------------------------------------
|"TEAM_1"      |"TEAM_2"   |"SEED_1"  |"SEED_2"  |"REGION"  |
-------------------------------------------------------------
|Purdue        |Marquette  |1         |2         |W         |
|Alabama       |Baylor     |1         |3         |X         |
|Houston       |Texas      |1         |2         |Y         |
|St Mary's CA  |Gonzaga    |5         |3         |Z         |
-------------------------------------------------------------

In [105]:
elite_8 = elite_8_matchups.select('WTEAMID2','LTEAMID2','W_SEED','L_SEED')

season = (
    session.table("FINAL_SEASON_STATS").filter(F.col("season") == 2023).drop("W_SEASON")
)

season_w = season.select(*[F.col(col).alias(f"W_{col}") for col in season.columns])

season_l = season.select(*[F.col(col).alias(f"L_{col}") for col in season.columns])

df1 = elite_8.join(season_w, season_w.w_teamid == elite_8.wTEAMID2)

df2 = df1.join(season_l, season_l.l_teamid == elite_8.lTEAMID2)

elite_8 = df2.drop('WTEAMID2','lTEAMID2')

elite_8.count()

4

In [106]:
result = all_rounds.predict(elite_8)

teams = session.table("m_teams")

result = (
    result.select(
        "l_teamID",
        "l_seed",
        "w_seed",
        "l_region",
        "w_teamid",
        "w_region",
        "pred_win_indicator",
    )
)

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

elite_8_results = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select(
        "l_teamid",
        "w_teamid",
        "L_TEAM_NAME",
        "l_seed",
        "w_seed",
        "l_region",
        "W_TEAM_NAME",
        "w_region",
        "PRED_WIN_INDICATOR",
    )
)

In [107]:
elite_8_winners = elite_8_results.with_column(
    "W_TEAM_ID",
    when((elite_8_results.PRED_WIN_INDICATOR == 1), elite_8_results.w_teamid)
    .otherwise(elite_8_results.l_teamID),
).with_column(
    "W_TEAM_NAME",
    when((elite_8_results.PRED_WIN_INDICATOR == 1), elite_8_results.w_team_name)
    .otherwise(elite_8_results.l_team_name),
).with_column(
    "W_SEED",
    when((elite_8_results.PRED_WIN_INDICATOR == 1), elite_8_results.w_seed)
    .otherwise(elite_8_results.l_seed),
).with_column(
    "W_REGION",
    when((elite_8_results.PRED_WIN_INDICATOR == 1), elite_8_results.w_region)
    .otherwise(elite_8_results.l_region)
).select("W_TEAM_ID","W_TEAM_NAME","W_SEED","W_REGION")

# Elite 8 winners

In [108]:
elite_8_winners.sort('W_REGION').show(20)

-------------------------------------------------------
|"W_TEAM_ID"  |"W_TEAM_NAME"  |"W_SEED"  |"W_REGION"  |
-------------------------------------------------------
|1266         |Marquette      |2         |W           |
|1104         |Alabama        |1         |X           |
|1222         |Houston        |1         |Y           |
|1211         |Gonzaga        |3         |Z           |
-------------------------------------------------------

In [109]:
df1 = elite_8_winners.filter(F.col("W_REGION") == "W")

df2 = elite_8_winners.filter(F.col("W_REGION") == "X").select(
    F.col("W_TEAM_ID").alias("TEAM_2"),
    F.col("W_TEAM_NAME").alias("W_TEAM_NAME_2"),
    F.col("W_SEED").alias("SEED_2"),
    F.col("W_REGION").alias("REGION_2"),
)

df3 = df1.join(df2)

df4 = elite_8_winners.filter(F.col("W_REGION") == "Y")

df5 = elite_8_winners.filter(F.col("W_REGION") == "Z").select(
    F.col("W_TEAM_ID").alias("TEAM_2"),
    F.col("W_TEAM_NAME").alias("W_TEAM_NAME_2"),
    F.col("W_SEED").alias("SEED_2"),
    F.col("W_REGION").alias("REGION_2"),
)

df6 = df4.join(df5)

final_four_matchups = df3.union(df6).select(
    F.col('W_TEAM_NAME'),
    F.col('W_REGION'),
    F.col("W_TEAM_ID").alias("WTEAMID2"),
    F.col('W_SEED'),
    F.col("W_TEAM_NAME_2").alias("L_TEAM_NAME"),
    F.col("REGION_2").alias("L_REGION"),
    F.col("TEAM_2").alias("LTEAMID2"),
    F.col("SEED_2").alias("L_SEED"),
)

# FINAL FOUR!

In [110]:
final_four_matchups.select(
    F.col("W_TEAM_NAME").alias("TEAM_1"),
    F.col("L_TEAM_NAME").alias("TEAM_2"),
    F.col("W_SEED").alias("SEED_1"),
    F.col("L_SEED").alias("SEED_2"),
    F.col("W_REGION").alias("REGION"),
).sort("REGION").show(20)

---------------------------------------------------------
|"TEAM_1"   |"TEAM_2"  |"SEED_1"  |"SEED_2"  |"REGION"  |
---------------------------------------------------------
|Marquette  |Alabama   |2         |1         |W         |
|Houston    |Gonzaga   |1         |3         |Y         |
---------------------------------------------------------

In [111]:
final_four = final_four_matchups.select('WTEAMID2','LTEAMID2','W_SEED','L_SEED')

season = (
    session.table("FINAL_SEASON_STATS").filter(F.col("season") == 2023).drop("W_SEASON")
)

season_w = season.select(*[F.col(col).alias(f"W_{col}") for col in season.columns])

season_l = season.select(*[F.col(col).alias(f"L_{col}") for col in season.columns])

df1 = final_four.join(season_w, season_w.w_teamid == final_four.wTEAMID2)

df2 = df1.join(season_l, season_l.l_teamid == final_four.lTEAMID2)

final_four = df2.drop('WTEAMID2','lTEAMID2')

final_four.count()

2

In [112]:
result = all_rounds.predict(final_four)

teams = session.table("m_teams")


result = (
    result.select(
        "l_teamID",
        "l_seed",
        "w_seed",
        "l_region",
        "w_teamid",
        "w_region",
        "pred_win_indicator",
    )
)

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

final_four_results = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select(
        "l_teamid",
        "w_teamid",
        "L_TEAM_NAME",
        "l_seed",
        "w_seed",
        "l_region",
        "W_TEAM_NAME",
        "w_region",
        "PRED_WIN_INDICATOR",
    )
)

In [113]:
final_four_winners = final_four_results.with_column(
    "W_TEAM_ID",
    when((final_four_results.PRED_WIN_INDICATOR == 1), final_four_results.w_teamid)
    .otherwise(final_four_results.l_teamID),
).with_column(
    "W_TEAM_NAME",
    when((final_four_results.PRED_WIN_INDICATOR == 1), final_four_results.w_team_name)
    .otherwise(final_four_results.l_team_name),
).with_column(
    "W_SEED",
    when((final_four_results.PRED_WIN_INDICATOR == 1), final_four_results.w_seed)
    .otherwise(final_four_results.l_seed),
).with_column(
    "W_REGION",
    when((final_four_results.PRED_WIN_INDICATOR == 1), final_four_results.w_region)
    .otherwise(final_four_results.l_region)
).select("W_TEAM_ID","W_TEAM_NAME","W_SEED","W_REGION")

In [114]:
final_four_winners.sort('W_REGION').show(20)

-------------------------------------------------------
|"W_TEAM_ID"  |"W_TEAM_NAME"  |"W_SEED"  |"W_REGION"  |
-------------------------------------------------------
|1266         |Marquette      |2         |W           |
|1222         |Houston        |1         |Y           |
-------------------------------------------------------

In [115]:
df1 = final_four_winners.cache_result()
df2 = final_four_winners.cache_result()

championship_matchup = df1.join(df2).select(
    df1.w_team_name.alias('W_TEAM_NAME'),
    df1.w_region.alias('W_REGION'),
    df1.w_team_id.alias('WTEAMID2'),
    df1.w_seed.alias('W_SEED'),
    df2.w_team_name.alias('L_TEAM_NAME'),
    df2.w_region.alias('L_REGION'),
    df2.w_team_id.alias('LTEAMID2'),
    df2.w_seed.alias('L_SEED'),
).filter(F.col("WTEAMID2") != F.col("LTEAMID2")).limit(1)

# CHAMPIONSHIP!

In [116]:
championship_matchup.select(
    F.col("W_TEAM_NAME").alias("TEAM_1"),
    F.col("L_TEAM_NAME").alias("TEAM_2"),
    F.col("W_SEED").alias("SEED_1"),
    F.col("L_SEED").alias("SEED_2"),
    F.col("W_REGION").alias("REGION"),
).sort("REGION").show(20)

---------------------------------------------------------
|"TEAM_1"  |"TEAM_2"   |"SEED_1"  |"SEED_2"  |"REGION"  |
---------------------------------------------------------
|Houston   |Marquette  |1         |2         |Y         |
---------------------------------------------------------

In [117]:
championship = championship_matchup.select('WTEAMID2','LTEAMID2','W_SEED','L_SEED')

season = (
    session.table("FINAL_SEASON_STATS").filter(F.col("season") == 2023).drop("W_SEASON")
)

season_w = season.select(*[F.col(col).alias(f"W_{col}") for col in season.columns])

season_l = season.select(*[F.col(col).alias(f"L_{col}") for col in season.columns])

df1 = championship.join(season_w, season_w.w_teamid == championship.wTEAMID2)

df2 = df1.join(season_l, season_l.l_teamid == championship.lTEAMID2)

championship = df2.drop('WTEAMID2','lTEAMID2')

championship.count()

1

In [118]:
result = all_rounds.predict(championship)

teams = session.table("m_teams")
for col in teams.columns:
    teams = teams.withColumnRenamed(col, col.upper())

result = (
    result.select(
        "l_teamID",
        "l_seed",
        "w_seed",
        "l_region",
        "w_teamid",
        "w_region",
        "pred_win_indicator",
    )
)

res_teamsl = (
    result.join(teams, result.col("L_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "l_team_name")
    .drop("firstd1season", "lastd1season")
)
res_teamsl = res_teamsl.cache_result()

championship_results = (
    res_teamsl.join(teams, result.col("W_TEAMID") == teams.col("TEAMID"))
    .with_column_renamed("teamname", "w_team_name")
    .select(
        "l_teamid",
        "w_teamid",
        "L_TEAM_NAME",
        "l_seed",
        "w_seed",
        "l_region",
        "W_TEAM_NAME",
        "w_region",
        "PRED_WIN_INDICATOR",
    )
)

In [119]:
championship_results.show()

----------------------------------------------------------------------------------------------------------------------------------
|"L_TEAMID"  |"W_TEAMID"  |"L_TEAM_NAME"  |"L_SEED"  |"W_SEED"  |"L_REGION"  |"W_TEAM_NAME"  |"W_REGION"  |"PRED_WIN_INDICATOR"  |
----------------------------------------------------------------------------------------------------------------------------------
|1266        |1222        |Marquette      |2         |1         |W           |Houston        |Y           |1.0                   |
----------------------------------------------------------------------------------------------------------------------------------

In [120]:
champion = championship_results.with_column(
    "W_TEAM_ID",
    when((championship_results.PRED_WIN_INDICATOR == 1), championship_results.w_teamid)
    .otherwise(championship_results.l_teamID),
).with_column(
    "W_TEAM_NAME",
    when((championship_results.PRED_WIN_INDICATOR == 1), championship_results.w_team_name)
    .otherwise(championship_results.l_team_name),
).with_column(
    "W_SEED",
    when((championship_results.PRED_WIN_INDICATOR == 1), championship_results.w_seed)
    .otherwise(championship_results.l_seed),
).with_column(
    "W_REGION",
    when((championship_results.PRED_WIN_INDICATOR == 1), championship_results.w_region)
    .otherwise(championship_results.l_region)
).select("W_TEAM_ID","W_TEAM_NAME","W_SEED","W_REGION")

# CHAMPION!

In [121]:
champion.show()

-------------------------------------------------------
|"W_TEAM_ID"  |"W_TEAM_NAME"  |"W_SEED"  |"W_REGION"  |
-------------------------------------------------------
|1222         |Houston        |1         |Y           |
-------------------------------------------------------

# Predict Play in games today

In [123]:
season = (
    session.table("FINAL_SEASON_STATS").filter(F.col("season") == 2024).drop("W_SEASON")
)
season.show()

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"CONF_ACC"  |"CONF_AEC"  |"CONF_A_SUN"  |"CONF_A_TEN"  |"CONF_BIG_EAST"  |"CONF_BIG_SKY"  |"CONF_BIG_SOUTH"  |"CONF_BIG_TEN"  |"CONF_BIG_TWELVE"  |"CONF_BIG_WEST"  |"CONF_CAA"  |"CONF_CUSA"  |"CONF_GWC"  |"CONF_HORIZON"  |"CONF_IND"  |"CONF_IVY"  |"CONF_MAAC"  |"CONF_MAC"  |"CONF_MEAC"  |"CONF_MID_CONT"  |"CONF_MVC"  |"CONF_MWC"  |"CONF_NEC"  |"CONF_OVC"  |"CONF_PAC_TEN"  |"CONF_PAC_TWELVE"  |"CONF_PATRIOT"  |"CONF_SEC"  |"CONF_SOUTHERN"  |"CONF_SOUTHLAND"  |"CONF_SUMMIT"  |"CONF_SUN_BELT"  |"CONF_SWAC"  |"CONF_WAC"  |"CONF_WCC"  |"SEASON"  |"TEAMID"  |"SCORE_MEAN"  |"FGM_MEAN"  |"FGA_MEAN"  |"FGM3_MEAN"  |"FGA3_MEAN"  |"FTM_MEAN"  |"FTA_MEAN"  |"OR_MEAN"  |"DR_MEAN"  |"AST_MEAN"  |"TO_MEAN"  |"STL_MEAN"  |"BLK_MEAN"  |"PF_MEAN"  |"SCORE_MEDIAN"  |"FGM_MEDIAN"  |"FGA_MEDIAN"  |"FGM3_MEDIAN"  |"FGA3_MEDIAN"  |"FTM_MEDIAN"  |"FTA_MEDIAN"  |"OR_MEDIAN"  |"DR_MEDIAN"  |"AST_MEDIAN"  |"TO_MEDIAN"  |"STL_MEDIAN"  |"BLK_MEDIAN"  |"PF_MEDIAN"  |"SCORE_STDDEV"      |"FGM_STDDEV"        |"FGA_STDDEV"        |"FGM3_STDDEV"       |"FGA3_STDDEV"       |"FTM_STDDEV"        |"FTA_STDDEV"       |"OR_STDDEV"         |"DR_STDDEV"         |"AST_STDDEV"        |"TO_STDDEV"         |"STL_STDDEV"        |"BLK_STDDEV"        |"PF_STDDEV"         |"WLOCN"  |"WLOCH"  |"WLOCA"  |"WINMARGINMEDIAN"  |"WINMARGINMEAN"  |"LOSEMARGINMEDIAN"  |"LOSEMARGINMEAN"  |"WON_CONFERENCE"  |"TOTAL_WINS"  |"REGION"  |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|0           |0           |0             |0             |0                |0               |0                 |0               |0                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |1           |0                |0                 |0              |0                |0            |0           |0           |2024      |1280      |74.764706     |26.382353   |58.029412   |7.205882     |22.147059    |14.794118   |22.000000   |10.676471  |24.411765  |13.941176   |12.294118  |8.088235    |3.088235    |16.735294  |73.500          |26.000        |57.000        |7.000          |21.000         |16.500        |22.000        |11.000       |23.000       |14.000        |12.000       |8.000         |3.000         |17.000       |10.114672263598065  |4.156154352282889   |6.842316201404317   |2.683049011852001   |6.00571619376074    |5.2210495113530575  |7.058199628800534  |3.318639630933133   |4.76170106159553    |4.953977089167854   |2.928743757995909   |2.9783831184050182  |2.108678259004915   |2.863657626183689   |8        |11       |2        |13.000             |14.714286        |7.000               |8.846154          |0                 |21.0          |X         |
|0           |0           |0             |0             |0                |0               |0                 |0               |1                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1140      |81.848485     |29.393939   |63.575758   |11.212121    |32.212121    |11.848485   |16.060606   |10.121212  |26.090909  |18.606061   |10.363636  |5.939394    |3.000000    |17.696970  |84.000          |29.000        |64.000        |12.000         |32.000         |11.000        |16.000        |10.000       |26.000       |18.000        |10.000       |6.000         |3.000         |18.000       |12.542730005863955  |5.5954188404443865  |7.945243482738587   |2.9554776263744578  |6.0299127688549525  |6.892573974938535   |7.757816187562065  |3.7479791888429688  |4.856462395612675   |5.279319274300428   |3.621275465909767   |2.4992422851736484  |2.1360009363293826  |3.1173390896724724  |4        |16       |3        |14.000             |21.173913        |9.500               |9.300000          |0                 |23.0          |W         |
|0           |0           |0             |0             |0                |0               |0                 |0               |0                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |1           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1161      |75.125000     |27.093750   |56.156250   |7.156250     |21.531250    |13.781250   |18.281250   |6.437500   |23.375000  |17.812500   |9.625000   |6.125000    |3.031250    |17.062500  |75.500          |27.000        |53.500        |6.000          |21.000         |13.500        |18.500        |6.500        |22.000       |17.500        |9.000        |6.000         |3.000         |17.000       |10.739586118654666  |4.372637647919159   |6.9147312312193305  |2.1115560612969766  |4.158042207577984   |5.829482224005834   |7.484325019666102  |3.2222763692768503  |5.302160220136694   |5.208166663999915   |2.392865646040329   |2.498386479310197   |1.3556186779474528  |3.8932323331648218  |5        |13       |4        |9.500              |12.090909        |5.500               |7.100000          |0                 |22.0          |Y         |
|0           |0           |0             |0             |0                |0               |0                 |0               |1                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1222      |73.029412     |26.352941   |60.735294   |7.705882     |22.235294    |12.617647   |18.176471   |12.352941  |22.411765  |12.941176   |8.352941   |10.000000   |4.735294    |17.794118  |75.000          |27.000        |61.000        |8.000          |22.000         |11.000        |15.500        |12.000       |22.000       |13.000        |8.500        |9.500         |4.000         |18.000       |10.40537534162031   |4.464556416935506   |4.9378490256385925  |2.1815952878570304  |4.539782593913501   |5.510401800231994   |8.50479576474356   |3.691779245837974   |4.881117904742724   |3.0643717137449236  |2.837864690220448   |3.77391361851328    |2.5263319259353074  |3.282454874023404   |6        |17       |7        |16.000             |19.733333        |8.500               |11.500000         |0                 |30.0          |Z         |
|0           |0           |0             |0             |0                |0               |0                 |1               |0                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1321      |73.687500     |26.281250   |57.250000   |8.312500     |21.093750    |12.812500   |17.125000   |7.156250   |21.718750  |15.625000   |8.093750   |6.906250    |3.281250    |17.750000  |72.000          |25.500        |58.000        |8.000          |21.000         |13.000        |17.000        |7.000        |21.500       |15.500        |7.500        |7.000         |3.000         |17.000       |12.171986608602559  |5.460913202020336   |6.420732512727811   |2.347785552387611   |4.637570053379248   |5.45028852447281    |6.612549130252266  |3.3898269867354585  |4.58070551334617    |5.314314160830163   |3.846736148996965   |2.4277876760540655  |2.203141166607351   |4.648967949986319   |2        |15       |4        |11.000             |11.714286        |8.000               |8.727273          |0                 |21.0          |W         |
|0           |0           |0             |0             |0                |0               |0                 |0               |0                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |1            |0           |0           |2024      |1212      |65.129032     |22.580645   |52.354839   |5.322581     |15.612903    |14.645161   |20.741935   |7.741935   |20.612903  |9.161290    |12.741935  |7.129032    |3.096774    |16.161290  |66.000          |23.000        |52.000        |5.000          |16.000         |14.000        |20.000        |8.000        |20.000       |9.000         |13.000       |7.000         |2.000         |16.000       |11.438944968833445  |3.748548118938851   |5.5650599277995205  |2.2566508369705756  |4.492047973920136   |6.364214484129207   |8.217735880399175  |2.780500494515331   |3.988963273834443   |3.406824327728097   |3.889882131890374   |2.825384221659065   |2.005905281911387   |4.017435127043123   |4        |6        |7        |8.000              |8.294118         |14.500              |18.357143         |1                 |17.0          |Y         |
|0           |0           |0             |1             |0                |0               |0                 |0               |0                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1182      |70.058824     |24.529412   |56.588235   |7.617647     |22.470588    |13.382353   |18.735294   |8.764706   |22.911765  |13.205882   |11.352941  |7.470588    |4.382353    |17.264706  |68.000          |24.000        |57.000        |7.000          |21.000         |13.000        |18.000        |8.000        |23.000       |12.500        |11.000       |7.000         |4.000         |18.000       |9.174870734784223   |4.024435115640455   |5.45014678701409    |2.913029351036477   |5.361113037420495   |5.662287258696789   |8.414665471663149  |3.838077383274079   |4.3160563017643785  |3.7641000252384367  |2.8485227750537647  |2.9463412904821467  |2.6743982500742107  |4.601112039496539   |6        |12       |5        |9.000              |9.478261         |10.000              |9.090909          |1                 |23.0          |W         |
|1           |0           |0             |0             |0                |0               |0                 |0               |0                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1301      |76.361111     |27.388889   |60.972222   |7.055556     |20.388889    |14.527778   |19.805556   |9.055556   |23.583333  |12.694444   |9.222222   |7.416667    |3.500000    |16.361111  |80.000          |28.000        |62.000        |7.500          |20.000         |14.500        |20.500        |8.500        |24.000       |13.000        |9.000        |7.000         |3.000         |16.000       |10.999098099389785  |3.7361383807348463  |5.43788883667182    |2.776888726614734   |5.309171498454349   |6.411980349314867   |7.25778182367037   |3.656262299124613   |3.872061079063707   |3.2144268540441234  |2.948230486240857   |3.06477682711156    |1.7154757357654464  |4.38277651723197    |6        |12       |4        |8.500              |11.681818        |8.500               |8.928571          |1                 |22.0          |Z         |
|0           |0           |0             |0             |0                |0               |0                 |0               |0                  |0                |0           |1            |0           |0               |0           |0           |0            |0           |0            |0                |0           |0           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1443      |79.100000     |28.900000   |62.033333   |6.600000     |19.200000    |14.700000   |20.433333   |8.466667   |27.100000  |12.866667   |13.333333  |7.700000    |3.166667    |18.666667  |79.000          |28.000        |61.000        |6.500          |19.000         |13.000        |20.500        |8.500        |27.000       |13.500        |13.500       |7.000         |3.000         |19.000       |9.282352557406986   |4.381386995005121   |6.122222553942318   |2.9196126455405005  |4.389643037879048   |4.587464223293736   |5.593612964801909  |3.0255616007610886  |4.269781493238266   |4.006316887117143   |3.808641096244171   |3.2499336916312616  |1.6832507240455892  |4.520705918327358   |4        |9        |6        |10.000             |10.526316        |4.000               |5.000000          |1                 |19.0          |Z         |
|0           |0           |0             |0             |0                |0               |0                 |0               |0                  |0                |0           |0            |0           |0               |0           |0           |0            |0           |0            |0                |0           |1           |0           |0           |0               |0                  |0               |0           |0                |0                 |0              |0                |0            |0           |0           |2024      |1361      |74.187500     |25.656250   |58.437500   |6.906250     |22.093750    |15.968750   |21.906250   |9.750000   |24.125000  |13.031250   |10.281250  |7.250000    |4.062500    |17.718750  |73.500          |26.000        |58.000        |7.000          |22.000         |16.000        |22.000        |9.000        |24.500       |13.000        |10.000       |8.000         |4.000         |18.500       |8.96026171492775    |3.823605628199645   |6.298681369937679   |2.115371834926427   |4.328147756257866   |6.463217851813445   |8.46381054844684   |3.7759853018781735  |4.156223526231476   |3.947104888396051   |4.025999130650677   |2.77081558390305    |1.949979230658624   |3.977634095791115   |4        |12       |6        |12.000             |12.863636        |5.500               |6.400000          |0                 |22.0          |W         |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [124]:
grambling = (
    session.table("MEN.FINAL_SEASON_STATS").drop('N','H','A')
).filter(F.col('SEASON') == 2024).filter(F.col('TEAMID') == 1212).drop('SEASON').limit(1)

montana_st = (
    session.table("MEN.FINAL_SEASON_STATS").drop('N','H','A')
).filter(F.col('SEASON') == 2024).filter(F.col('TEAMID') == 1286).drop('SEASON').limit(1)

boise_st = (
    session.table("MEN.FINAL_SEASON_STATS").drop('N','H','A')
).filter(F.col('SEASON') == 2024).filter(F.col('TEAMID') == 1129).drop('SEASON').limit(1)

colorado = (
    session.table("MEN.FINAL_SEASON_STATS").drop('N','H','A')
).filter(F.col('SEASON') == 2024).filter(F.col('TEAMID') == 1160).drop('SEASON').limit(1)

for column in grambling.columns:
        grambling = grambling.withColumnRenamed(column, f"W_{column}")

for column in montana_st.columns:
        montana_st = montana_st.withColumnRenamed(column, f"L_{column}")

play_in = grambling.join(montana_st)

In [125]:
columns_to_add = [col for col in test.columns if col not in play_in.columns]
columns_to_add

['SEASON', 'W_SCORE', 'L_SCORE', 'ROUND', 'W_SEED', 'L_SEED', 'WIN_INDICATOR']

In [ ]:
columns_to_add = [col for col in test.columns if col not in play_in.columns]

# For each column to add, add it to df1 with a default value of 0
for col in columns_to_add:
    play_in = play_in.withColumn(col, lit(0))

In [126]:
play_in = play_in.withColumn('L_SEED', lit(16))
play_in = play_in.withColumn('W_SEED', lit(16))

In [129]:
play_in_results = all_rounds.predict_proba(play_in)
play_in_results.with_column_renamed(
    '"predict_proba_1"', "grambling_win_prob"
).select('grambling_win_prob').show()

------------------------
|"GRAMBLING_WIN_PROB"  |
------------------------
|0.027495671063661575  |
------------------------

In [135]:
boise_st = (
    session.table("MEN.FINAL_SEASON_STATS").drop('N','H','A')
).filter(F.col('SEASON') == 2024).filter(F.col('TEAMID') == 1129).drop('SEASON').limit(1)

colorado = (
    session.table("MEN.FINAL_SEASON_STATS").drop('N','H','A')
).filter(F.col('SEASON') == 2024).filter(F.col('TEAMID') == 1160).drop('SEASON').limit(1)

In [136]:
for column in boise_st.columns:
        boise_st = boise_st.withColumnRenamed(column, f"W_{column}")

for column in colorado.columns:
        colorado = colorado.withColumnRenamed(column, f"L_{column}")

play_in = boise_st.join(colorado)

columns_to_add = [col for col in test.columns if col not in play_in.columns]


play_in = play_in.withColumn('L_SEED', lit(10))
play_in = play_in.withColumn('W_SEED', lit(10))

In [137]:
play_in_results = all_rounds.predict_proba(play_in)
play_in_results.with_column_renamed(
    '"predict_proba_1"', "boise_st_win_prob"
).select('boise_st_win_prob').show()

-----------------------
|"BOISE_ST_WIN_PROB"  |
-----------------------
|0.39441338181495667  |
-----------------------

In [127]:
# # Point to the registry

# reg = Registry(session=session)
# m = reg.get_model("MARCHMADNESS")
# m.default = 'V_1'

# # Get the default version of your model (Model with best accuracy in our case)

# mv = reg.get_model("MARCHMADNESS").default

# remote_prediction = mv.run(play_in, function_name="predict_proba")
# remote_prediction.drop('"output_feature_0"').with_column_renamed(
#     '"output_feature_1"', "grambling_win_prob"
# ).select('grambling_win_prob').show()

ValueError: (2112)
Data Validation Error when validating your Snowpark DataFrame.
If using the normalized names from model signatures, there are the following errors:
[ValueError('(2112) Data Validation Error in feature W_WLOCN: Feature type DataType.INT64 is not met by column W_WLOCN because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature W_WLOCH: Feature type DataType.INT64 is not met by column W_WLOCH because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature W_WLOCA: Feature type DataType.INT64 is not met by column W_WLOCA because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature L_WLOCN: Feature type DataType.INT64 is not met by column L_WLOCN because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature L_WLOCH: Feature type DataType.INT64 is not met by column L_WLOCH because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature L_WLOCA: Feature type DataType.INT64 is not met by column L_WLOCA because of its original type VariantType()')]

If using the inferred names from model signatures, there are the following errors:
[ValueError('(2112) Data Validation Error in feature W_WLOCN: Feature type DataType.INT64 is not met by column W_WLOCN because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature W_WLOCH: Feature type DataType.INT64 is not met by column W_WLOCH because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature W_WLOCA: Feature type DataType.INT64 is not met by column W_WLOCA because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature L_WLOCN: Feature type DataType.INT64 is not met by column L_WLOCN because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature L_WLOCH: Feature type DataType.INT64 is not met by column L_WLOCH because of its original type VariantType()'), ValueError('(2112) Data Validation Error in feature L_WLOCA: Feature type DataType.INT64 is not met by column L_WLOCA because of its original type VariantType()')]

In [ ]:
for column in boise_st.columns:
        boise_st = boise_st.withColumnRenamed(column, f"W_{column}")

for column in colorado.columns:
        colorado = colorado.withColumnRenamed(column, f"L_{column}")

play_in = boise_st.join(colorado)

columns_to_add = [col for col in test.columns if col not in play_in.columns]

# For each column to add, add it to df1 with a default value of 0
for col in columns_to_add:
    play_in = play_in.withColumn(col, lit(0))

play_in = play_in.drop(['W_CTWINS','W_AVERAGECTSCORE','L_CTWINS','L_AVERAGECTSCORE'])
play_in = play_in.drop(['W_WLOCN','W_WLOCH','W_WLOCA','L_WLOCN','L_WLOCH','L_WLOCA']) #variants
play_in = play_in.withColumn('L_SEED', lit(10))
play_in = play_in.withColumn('W_SEED', lit(10))

# Point to the registry

reg = Registry(session=session)
m = reg.get_model("MARCHMADNESS")
m.default = 'V_5'

# Get the default version of your model (Model with best accuracy in our case)

mv = reg.get_model("MARCHMADNESS").default

remote_prediction = mv.run(play_in, function_name="predict_proba")
remote_prediction.drop('"output_feature_0"').with_column_renamed(
    '"output_feature_1"', "boise_st_win_prob"
).select('boise_st_win_prob').show()